### PR TITLE
remove CTEs for schema tests

### PR DESCRIPTION
**Pull request by cmcarthur**
for #528 

reopened from #534

### CODE REVIEW

**Comment by cmcarthur** [comment]
cc @ronnyli

**Comment by ronnyli** [comment]
nice, it passed this time! I'm assuming circle checks if the changes work on big-query, redshift, postgres, and snowflake? I only personally tested on Postgres so far.

**Comment by cmcarthur** [comment]
@ronnyli we have it set up to check postgres, bigquery and snowflake & drew played around with this.

thanks again for contributing! 🍺

**Comment by ronnyli** [comment]
great! Thanks for your help

**Comment by drewbanin** [comment]
great work @ronnyli :)

**Pull request merged**
