### PR TITLE
Feature: reports

### LINKED ISSUE #2730: New node type: reports
**Edit: I previously called these `exposures`. I've changed it to `report` to keep it more tangible for this first version.

dbt Core needs to have a semantic understanding of a `report`. A "report" is a generalization of a "dashboard", though it could also be an ML model, Jupyter notebook, R Shiny app, in-app data viz, etc.

The `report` node serves two purposes:
1. Define a set of models as dependencies
2. Define metadata to populate an embed tile and special dbt-docs "landing page"

### Why?

* We want to be able to push information about data quality and lineage from dbt into external tools. Exposures should be the Core side of that contract.
* The same reason we added `sources`: there's a big piece missing from the DAG today. Once downstream uses of dbt models are registered as `reports`, dbt project maintainers can start asking questions like:
    * Which models are our most critical dependencies?
    * Which final models are only used by exposures with very few/irregular views?
    * Which final models aren't used at all?

### Tentative spec
**Edit: updated based on comments below**

_models/anything.yml_
```yml
version: 2

exposures:
  - name: orders_dash

    type: dashboard # one of: {dashboard, notebook, analysis, ml, application}
    url: https://fishtown.looker.com/dashboards/1
    maturity: high # i.e. importance/usage/QA/SLA/etc. one of: {low, medium, high}

    description: >

      This is a dashboard of monthly orders, with customer
      attributes as context.

    depends_on:
      - ref('fct_orders')
      - ref('dim_customer')
      - source('marketplace', 'currency_conversions')

    owner:
      email: jeremy@fishtownanalytics.com # required
      name: "Jeremy from FP&A" # optional
```

### Core functionality

By way of `depends_on`, I'd expect `dbt run -m +report:orders_dash` to run all upstream models, and `dbt test -m +report:orders_dash` to test all upstream nodes. `dbt run -m +report:*` would run all models upstream of all reports. An report cannot itself be run or have tests defined.

**Edit:** I changed this syntax to feel more like the `source:` model selector method. Rationale: `dbt run -m orders_dash` has no effect; it's worth calling out that this is a special thing.

### Open questions

1. What should be the docs "landing page" for a `report`? I'll write up a related dbt-docs issue
2. Crucially, we'll need a mechanism that can parse a report's `depends_on` from `manifest.json`, compile the list of _all_ upstream nodes, and then search in `run_results.json` and `sources.json` for all associated tests and freshness checks. Where should that mechanism live, exactly?
3. `owner`: There is added benefit (and constraint) to tying this to a dbt Cloud user ID. Should we try to make a mapping via email only, instead?
4. `type` + `maturity`: Should we constrain the set of options here? Offer them as free text fields? I like the eventual idea of summarizing things like:
```
fct_orders is directly exposed in:
3 dashboards, of varying maturity (high: 2, medium: 1)
1 low-maturity ML pipeline
2 medium-maturity apps

fct_orders indirectly powers:
2 medium-maturity dashboards
```
Maybe that's in dbt-docs, maybe that's an `ls` command, maybe it's a pipe dream. This is the piece that feels least critical for the first version.

@drewbanin to help suss out some answers

### Future work (not v1)

* Can reports declare non-model nodes in their `depends_on`? (Could reports depend on _other_ reports?)
* Can reports modify expectations of upstream tests? I could imagine overriding a test severity, or defining a set of tests to exclude from consideration.
* Can reports be tagged?
* Can they accept arbitrary additional fields (i.e. `meta`)?
* Can we closely tie `owner` to a dbt Cloud user by email? Purpose: configurable notification channels, asset rendering in dbt-docs

### PR DESCRIPTION
**Pull request by beckjake**
resolves #2730 

### Description
Add report nodes to dbt.

They participate in the graph (as a "sink": not ref-able, but can use `ref`/`source`). That means they also honor selector behavior, which means things like `dbt ls --select +my_report` behave, `dbt run --models '+state:modified'` runs all ancestors of a modified report, etc.

I made two changes unrelated to this PR:
 - bumped the dbt version to 0.18.1a1, as it was getting a bit confusing to run locally/switch branches around
 - I moved the RPC tests to a folder starting with `100` - this is a quality of life change to make it easier to run all non-RPC integration tests locally. I removed some unused folders there, too.

### Checklist
 - [X] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
 - [X] I have run this code in development and it appears to resolve the stated issue
 - [X] This PR includes tests, or tests are not required/relevant for this PR
 - [X] I have updated the `CHANGELOG.md` and added information about my change to the "dbt next" section.

### CODE REVIEW

**Comment by beckjake** [comment]
I'm not sure why it's not showing up here, but [this](https://dev.azure.com/fishtown-analytics/dbt/_build/results?buildId=2490&view=results) is the azure pipelines build for e96f4a5

**Review by jtcohen6 — APPROVED** [review]
This looks great! I messed around with some reports in our internal analytics project, there's a draft PR open there if you're curious.

Neither of these is a blocker for this PR, just things to discuss/modify between now and 0.18.0-rc1:

### node selection syntax

Because reports are like inverse sources, I had been thinking about a `report:` node selector. This would get us a few small things:
- Explicitness. A report can have the same name as a model (which feels ok), so we'd disambiguate between `dbt run -m +report:customers` and `dbt run -m +customers`.
- List all resources upstream of all reports: `dbt ls -s +report:*`. By the same token, list all resources that are _not_ exposed to any reports: `dbt ls --exclude +report:*`.

### dbt-docs

Open issue: https://github.com/fishtown-analytics/dbt-docs/issues/135

We just need to fix before we can release. They still work fine for projects that don't have `reports` defined.

**Comment by beckjake** [comment]
@jtcohen6 does that mean that reports shouldn't act like nodes in FQN selection? 

For example, sources can be selected with `source:` but they don't show up in the `fqn`/default selector. I think that would be good, it'd remove some ambiguity that currently exists where a report with the same name as a model.

**Comment by jtcohen6** [comment]
@beckjake That feels right to me. `dbt run -m +ambiguous_name` should default to the model, and excluding the same-named report has no functional difference since it isn't run. Is that a big change?

**Comment by beckjake** [comment]
I think it just involves tweaking the FQN selector to not look at reports and adding a selector that's a lot like `source:`, but for reports.

**Comment by beckjake** [comment]
That branch I just pushed is not quite right! Still need to handle package.report_name format, and need to fix report/source to output the correct selectors. Currently the `dbt ls` selector output is sort of wrong!

**Review by gshank — APPROVED** [review]

**Pull request merged**
