### PR TITLE
Re-instate hard-deleted records during snapshot

### LINKED ISSUE #2819: Re-instate hard-deleted records during snapshot
### Context

With PR #2749, dbt now can detect hard-deleted records and mark these records as invalidated. However as rightly mentioned on the PR, when the record returns (i.e. many-to-many link table), dbt won't see it.

> In any case, I'd welcome a new issue on the subject of handling hard-delete "returns" so we can move the discussion there and determine which is the most effective and concise approach.

_Originally posted by @jtcohen6 in https://github.com/fishtown-analytics/dbt/pull/2749#issuecomment-703977935_

### Describe the feature
Deleted records should be added back to the snapshot.

### Describe alternatives you've considered
State it as limitation in the docs <-- personally not a fan, we need this feature 😅 

### Additional context
Read the thread from the PR. Possible solution posted by by @seunghanhong in https://github.com/fishtown-analytics/dbt/pull/2749#issuecomment-703948574 but as replied by @jtcohen6 seems kinda over-engineered.

### Who will this benefit?
Anyone who was waiting for snapshotting hard-deletes in first place.

### Are you interested in contributing this feature?
Yes no problem, I'll dive in today to see if I can find an easy fix. Nevertheless, open to any suggestions you have 😃

### PR DESCRIPTION
**Pull request by joelluijmes**
resolves #2819

### Checklist
 - [x] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
 - [x] I have run this code in development and it appears to resolve the stated issue
 - [x] This PR includes tests, or tests are not required/relevant for this PR
 - [x] I have updated the `CHANGELOG.md` and added information about my change to the "dbt next" section.

### CODE REVIEW

**Review by jtcohen6 — COMMENTED** [review]
This looks great @joelluijmes! Nice work on adding the test for "revived" records. (I also quite like that as a descriptor.)

- Could you add a changelog entry?
- For economy's sake, you could cut the now-redundant filters (`where snapshotted_data.dbt_valid_to is null`) further down in the `snapshot_staging_table` macro

**Comment by joelluijmes** [comment]
Oh wups, didn't even see those filters 😅 
Didn't think changelog entry was necessary as this _feature_ kinda should have been present in the original PR. But I'll add it nevertheless 👍

**Comment by joelluijmes** [comment]
BQ test fails, but doesn't seem this change could have introduced it I'd say?

**Review by jtcohen6 — APPROVED** [review]
I think that test failure was a one-off, all is well upon re-running.

Thanks for the contribution @joelluijmes!

**Pull request merged**
