### PR TITLE
Fix/multiple ephemeral models share ctes

### PR DESCRIPTION
**Pull request by drewbanin**
This is a pretty sneaky issue

Model B => [Model A]
Model C => [Model B, Model A]

Previously, this would compile to:
```sql
-- model_c.sql

with dbt_cte__model_a as (
  select * from whatever
),

dbt_cte__model_a as (
  select * from whatever
)
dbt_cte__model_b as (
  select * from dbt_cte__model_a
)
...
```

Now, the `model_a` CTE is only injected once. I did this by changing `prepend_ctes` from a list to an OrderedDict. This works, because we 1) maintain the depth-first ordering of `prepend_ctes` provided by `recursively_prepend_ctes` and 2) don't duplicate CTEs because we're using a dict.

Super keen to hear your thoughts here @cmcarthur. I adjusted the voluptuous schema + wrote another test. Let me know

### CODE REVIEW

**Comment by drewbanin** [comment]
@cmcarthur I also made `tags` a set here. I made a bunch of changes where default args were objects eg.
```python
def method(self, a, b, tags=[]):
  pass

# became
def method(self, a, b, tags=None):
  if tags is None:
    tags = set()
  pass
```

I guess it hasn't been a problem thus far, but it's a bad idea to provide mutable objects as defaults to functions: http://effbot.org/zone/default-values.htm

**Comment by cmcarthur** [comment]
wow @ http://effbot.org/zone/default-values.htm. that's nuts. thanks for the heads up

**Comment by drewbanin** [comment]
@cmcarthur can i merge this? appveyor tests are broken, but I have another branch for that [here](https://github.com/fishtown-analytics/dbt/pull/321.

**Comment by drewbanin** [comment]
@cmcarthur yeah, you're right. Just changed. Will merge once circle tests pass

**Pull request merged**
