### PR TITLE
Make it possible to hide macros in docs

### LINKED ISSUE #2430: Hide macro from docs
### Describe the feature

We have some macros in our project that are not relevant to the consumers of our documentation site. Issue #1671 and pr #2179 came very close to delivering the necessary functionality to hide them.

### Describe alternatives you've considered

We can post-process the manifest.json file instead. This would be annoying and only fix the problem for us. A general solution would be better.

### Additional context

This is a trivial change.

### Who will this benefit?

This makes it easier to tweak the documentation site to work for less technical people.

### PR DESCRIPTION
**Pull request by alf-mindshift**
resolves #2430 

### Checklist
 - [x] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
 - [x] I have run this code in development and it appears to resolve the stated issue
 - [x] This PR includes tests, or tests are not required/relevant for this PR
 - [x] I have updated the `CHANGELOG.md` and added information about my change to the "dbt next" section.

### CODE REVIEW

**Comment by beckjake** [comment]
@cla-bot check

**Comment by beckjake** [comment]
@alf-mindshift, thanks for your contribution! The unit tests around serialization/deserialization are going to fail, and you'll probably also have to fix the `docs generate` tests, but this idea generally looks good! Please don't forget to add yourself as a contributor and this PR to `CHANGELOG.md` when this is ready, so we can give you credit in the release notes.

**Comment by alf-mindshift** [comment]
I rebased on top of octavius-catto. Let me know if I should rebase on top of marian-anderson instead.

**Comment by beckjake** [comment]
>I rebased on top of octavius-catto. Let me know if I should rebase on top of marian-anderson instead.

Please do! octavius-catto is really close to release, so it's bugfixes only right now. Once you do that I'll kick off the tests again

**Comment by beckjake** [comment]
Assuming the Windows tests pass, as I assume they will, I'm going to repair that merge conflict and merge. There's no need to go through all this again for a changelog conflict!

**Pull request merged**
