### PR TITLE
Merge bash completion script into dbt

### PR DESCRIPTION
**Pull request by jdub**
### Description

This branch merges the history of [fishtown-analytics/dbt-completion.bash](https://github.com/fishtown-analytics/dbt-completion.bash) and distributes the file in the dbt package.

It will require an accompanying change to [fishtown-analytics/homebrew-dbt](https://github.com/fishtown-analytics/homebrew-dbt) to install the completion script according to Homebrew standards.

Opening this as a draft because:

* I haven't updated the CHANGELOG
* I'm not wildly familiar with Python packaging, so this approach may be naïve
* Y'all may have more informed opinions about where the bash completion script should live
* I resolved the README.md conflict by dropping the completions content entirely, but that documentation should probably live somewhere (especially for non-Homebrew users)

### Checklist
 - [x] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
 - [x] I have run this code in development and it appears to resolve the stated issue
 - [x] This PR includes tests, or tests are not required/relevant for this PR
 - [ ] I have updated the `CHANGELOG.md` and added information about my change to the "dbt next" section.

### CODE REVIEW

**Comment by jdub** [comment]
@drewbanin Thoughts? Also, pls get cla-bot to recheck my status.

**Comment by jtcohen6** [comment]
@cla-bot check

**Comment by jtcohen6** [comment]
Hey @jdub, I'm appreciative of the thought (and git legwork) that went into this. After thinking about it for a while, and discussing with a few other folks on the team, I think we need to pass on merging the `dbt-completion` script into the main dbt codebase for now.

Every piece of the dbt codebase today is something we're committed to supporting, with regular updates and automated testing across a set of known platforms. That's just not true of `dbt-completion` at present. We haven't, for instance, upgraded the completion script to support all the new node selection operators and methods coming in v0.18.0. We don't really test the bash --> zsh port (hence https://github.com/fishtown-analytics/dbt-completion.bash/issues/6), or against any other shells for that matter.

I'm not opposed to merging `dbt-completion` into the main dbt codebase someday—or keeping it in a separate repo with a better, more explicit maintenance guarantee. That day will come when we have more engineers + QA capacity :) I hope we'll be able to say the same about experimental projects like [`dbt-sql-formatter`](https://github.com/fishtown-analytics/dbt-sql-formatter), too.

What do you think?

**Comment by jdub** [comment]
@jtcohen6 Sounds reasonable, thanks!

**Pull request closed without merging**
