### PR TITLE
Fix ENTRYPOINT to use 'dbt'

### LINKED ISSUE #2470: [0.17.0rc1] Broken Docker image entrypoint
### Describe the bug

The entrypoint for the image is invalid

### Steps To Reproduce

1. Pull the image: `docker pull fishtownanalytics/dbt:0.17.0rc1`
2. Run the image: 

```
docker run -it fishtownanalytics/dbt:0.17.0rc1
/bin/sh: 1: [dbt,: not found
```

### Expected behavior

The DBT help command is displayed

### Additional context

I plan on integrating DBT with our Airflow infrastructure as a container (we extend Airflow exclusively through containerized components)

### PR DESCRIPTION
**Pull request by dmateusp**
resolves #2470 

This is a copy of #2471 targeting `dev/octavius-catto` after @beckjake pointed out it is a bugfix

### Description

Change the entrypoint to be able to pass arguments and use DBT as it is used outside the container

### Checklist
 - [X] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
 - [X] I have run this code in development and it appears to resolve the stated issue
 - [X] This PR includes tests, or tests are not required/relevant for this PR
 - [ ] I have updated the `CHANGELOG.md` and added information about my change to the "dbt next" section.

### CODE REVIEW

**Comment by dmateusp** [comment]
Just rebased it against the bugfix branch, updated the CHANGELOG and removed the Dockerfile changes @beckjake

**Comment by beckjake** [comment]
I think you accidentally pulled in some tests from `dev/marian-anderson` in your changelog branch!

**Comment by dmateusp** [comment]
and oops I included files I didn't mean to include

**Comment by dmateusp** [comment]
Should be good now!

**Comment by dmateusp** [comment]
Added! Although the change is so small it feels undeserved 😆

**Pull request merged**
