### PR TITLE
Save args in run_results.json

### LINKED ISSUE #2510: capture dbt cli submitted command in run_results.json
### Describe the feature
capture dbt cli submitted command in run_results.json,
this is to help with logging/auditing, where we need some way to identify various runs. 

### Describe alternatives you've considered
no proper alternative, all the workarounds are fragile and short living at best, examples:
- if this invocation contains some specific marketing model then this is a marketing dbt run
- if the only tag that is present in my run is equal to 'hourly' then this is the hourly dbt run (depends on a strict set up of tags)

### Additional context
cross databases feature.

### Who will this benefit?
hopefully all dbt users, but main audience is dbt users trying to audit/investigate/optimize their runs

### LINKED ISSUE #2762: Remove injected_sql
### Describe the feature
Instead of adding `injected_sql` to the model during compilation, dbt should overwrite `compiled_sql`. There will probably be a lot of test fallout!

Split from #2671

### PR DESCRIPTION
**Pull request by gshank**
resolves #2510 

### Description

Save cli arguments (or the equivalent for the RPC server) to run_results.json

### Checklist
 - [x] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
 - [x] I have run this code in development and it appears to resolve the stated issue
 - [x] This PR includes tests, or tests are not required/relevant for this PR
 - [x] I have updated the `CHANGELOG.md` and added information about my change to the "dbt next" section.

### CODE REVIEW

**Comment by gshank** [comment]
RPC run_results args with just 'run':
    "args": {
        "log_format": "default",
        "write_json": true,
        "profiles_dir": "/Users/gerda/.dbt",
        "use_cache": true,
        "host": "0.0.0.0",
        "port": 8580,
        "version_check": true,
        "which": "rpc"
    }

cli dbt run_results args with just 'run':
    "args": {
        "log_format": "default",
        "write_json": true,
        "profiles_dir": "/Users/gerda/.dbt",
        "use_cache": true,
        "version_check": true,
        "which": "run",
        "rpc_method": "run"
    }

**Review by jtcohen6 — APPROVED** [review]
Everything working as expected.

It does seem odd to me that the RPC `run` method returns `{"which": "rpc"}`, whereas CLI `dbt run` returns `{"which": "run", "rpc_method": "run"}`. That's a matter out of scope for this particular issue, but worth addressing when we eventually get around to RPC <> CLI consistency.

**Comment by gshank** [comment]
I found the "which" and "rpc_method" thing a bit odd too. I looked into it, and the code has a bunch of methods specifying both in the CLI version (not the rpc code, which. has only the one that's been passed to it). And I wasn't quite sure of the purpose and wasn't sure if we'd lose information by removing, so I left it there.

**Comment by jtcohen6** [comment]
Yeah... I would like to rationalize those someday, but it's not in scope for this issue per se.

**Review by kwigley — APPROVED** [review]

**Pull request merged**
