### PR TITLE
update cryptography package and snowflake connector

### LINKED ISSUE #2896: Bump cryptography version with snowflake connector newer version
### Describe the bug
A clear and concise description of what the bug is. What command did you run? What happened?

Hi, we are trying to keep our dependencies up to date with security updates and I see that in the docker dependencies dbt has fixed version of cryptography 3.2 but in the snowflake plugin, it is still required cryptography version less than 3. The new snowflake connector library versions starting from  2.3.5 are supporting fixed cryptography version. Can we update those in dbt-snowflake plugin requirements too?

### Steps To Reproduce
In as much detail as possible, please provide steps to reproduce the issue. Sample data that triggers the issue, example model code, etc is all very helpful here.

You can try to install with pip dbt with dbt-snowflake plugin along side with new cryptography and snowflake client versions

### Expected behavior

Pip installs in the same virtual env cryptography version >= 3.2 along side with dbt-snowflake and snowfalke-connector version >= 2.3.5

### Screenshots and log output
If applicable, add screenshots or log output to help explain your problem.
log output:
```
15:59:22  dbt-snowflake 0.17.0 requires cryptography<3,>=2, but you'll have cryptography 3.2 which is incompatible.
15:59:22  dbt-snowflake 0.17.0 requires snowflake-connector-python==2.2.1, but you'll have snowflake-connector-python 2.3.5 which is incompatible.
```
### System information
**Which database are you using dbt with?**
- [ ] postgres
- [X] redshift
- [ ] bigquery
- [X] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
installed version: 0.17.0
   latest version: 0.18.1

Your version of dbt is out of date! You can find instructions for upgrading here:
https://docs.getdbt.com/docs/installation

Plugins:
  - bigquery: 0.17.0
  - snowflake: 0.17.0
  - redshift: 0.17.0
  - postgres: 0.17.0
```
Even though we still use 0.17.0 in the current latest master I still see vulnerable cryptography version

**The operating system you're using:**
MacOs and Linux

**The output of `python --version`:**
Python 3.6.5

### PR DESCRIPTION
**Pull request by plotneishestvo**
resolves #2896

### Description

Version update for snowflake-connector-python to support fixed version of cryptography library.

### Checklist
 - [x] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
 - [x] I have run this code in development and it appears to resolve the stated issue
 - [x] This PR includes tests, or tests are not required/relevant for this PR
 - [x] I have updated the `CHANGELOG.md` and added information about my change to the "dbt next" section.

### CODE REVIEW

**Comment by jtcohen6** [comment]
Thanks for this @plotneishestvo! The only blocker here is the CLA. Is that something you'll be able to sign?

**Comment by plotneishestvo** [comment]
> Thanks for this @plotneishestvo! The only blocker here is the CLA. Is that something you'll be able to sign?

@jtcohen6 I'm not sure, I'm currently working with our legal team to figure out what kind of policies we have in the company regarding contributing to open-source projects and who is able to sign an agreement. It can take a couple of days

**Comment by jtcohen6** [comment]
> It can take a couple of days

Okay, a couple of days is fine. I am hoping to have a beta or release candidate by the end of the week. Thanks for looking into it!

**Review by jtcohen6 — APPROVED** [review]
thanks for this @plotneishestvo!

**Comment by plotneishestvo** [comment]
> thanks for this @plotneishestvo!

Thank you @jtcohen6  too!

**Comment by NiallRees** [comment]
Thanks @plotneishestvo just run into this issue.

**Comment by jraede** [comment]
Looks like this has been merged but I'm still getting the issue. Which version of DBT contains the fix?

**Comment by kwigley** [comment]
@jraede this will go out with the v0.19.0 release when it is published. There should a release candidate (v0.19.0rc1) available soon that will include this as well.

**Pull request merged**
