### PR TITLE
Handle "meta:" key in schema/sources.yml

### LINKED ISSUE #1362: Feature: Configurable, arbitrary key in `schema.yml` to enhance documentation
### Feature description

*Following up to [this slack conversation](https://getdbt.slack.com/archives/C0VLZM3U2/p1553123052264200) with @drewbanin.*

Request is to add additional functionality in column-level documentation, specifically to identify upstream dependencies and transformation logic.

The example I used follows:

---

We’re building out our warehouse on top of Ruby-application generated data, so we’re frequently coalescing across polymorphic objects to summarize a type of event. a fun (...?) challenge is dealing with inconsistent naming conventions across the objects and normalizing them in our ETL.

Here’s a made-up example:

```sql
select
  orders.order_date
  , orders.item_type
  , coalesce(jackets.jacket_name, hats.name, shoes.shoe_style) as item_name
  , coalesce(jackets.color, hats.product_colorway, shoes.material_color) as item_color
  , count(*) as order_count
from orders
left join jackets
  on orders.item_fk = jackets.pk
  and orders.item_type = 'jacket'
left join hats
  on orders.item_fk = hats.pk
  and orders.item_type = 'hat'
left join shoes
  on orders.item_fk = shoes.pk
  and orders.item_type = 'shoe'
group by 1,2,3,4
```
We need to be able to communicate to end-users that the columns `item_name` and `item_color` are extracted from one of 3 objects, depending on the value of `item_type`

An additional use case of the column-level source/target lineage is communicating with our engineering partners which exact columns our tables depend on so they’re aware of downstream impact of altering/dropping those columns in the object upstream

I wonder if there’s any way to capture it in the sheama yaml? following on that made-up example earlier:

```yml
- name: agg_orders
  description: daily count of orders by item type, item name, and item color
  columns:
      - name: order_date
      - name: item_type
      - name: item_name
        depends:
            - name: jackets.jacket_name
            - name: hats.name
            - name: shoes.shoe_style
        transformation: coalesce(jackets.jacket_name, hats.name, shoes.shoe_style)
      - name: item_color
        depends:
            - name: jackets.color
            - name: hats.product_colorway
            - name: shoes.material_color
        transformation: coalesce(jackets.color, hats.product_colorway, shoes.material_color)
      - name: order_count
```

Drew suggested "some sort of `data:` key that can contain arbitrary configs, then some sort of macro that’s responsible for translating it into documentation".

### Who will this benefit?

**Owners of dbt warehouse**
  - single location to document table- and column-level details, attributes, and lineage instead of referencing `docs` blocks
  - streamlined process to identify upstream/downstream dependencies (tough to enforce consistent formatatting using markdown/`docs`)

**Consumers of dbt warehouse**
  - visibility into logical transformation associated with business logic
  - versioning to track historical changes in business logic/transformation logic

**Uptream of dbt warehouse; owners of production data**
  - visibility into downstream dependencies

### PR DESCRIPTION
**Pull request by tayloramurphy**
Closes #1362 

This PR adds the ability for people to use the key `meta:` to add arbitrary information to their schema.yml and sources.yml files. 

I have tested locally by having this in my schema.yml

```yaml
version: 2
models:
  - name: sfdc_account
    description: base model for SFDC Accounts tayloramurphy
    meta:
      owned: "@tayloramurphy"
    columns:
      - name: account_id
        meta:
          sensitivity: 1
```

and in my sources.yaml

```yaml
version: 2

sources:
  - name: salesforce
    database: '{{ env_var("SNOWFLAKE_LOAD_DATABASE") }}'
    schema: salesforce_stitch
    loader: Stitch
    loaded_at_field: _sdc_batched_at
    meta:
      owner: "@tayloramurphy_source_data"
    
    quoting:
      database: true
      schema: false
      identifier: false

    freshness:
        warn_after: {count: 8, period: hour}
        error_after: {count: 24, period: hour}

    tables: 
      - name: account
        description: '{{ doc("sfdc_account_source") }}'
        meta:
          sensitivity: "@tayloramurphy_source_data_table"
```

And was able to see in the manifest.json the data written appropriately. dbt also ran just fine.

### CODE REVIEW

**Comment by tayloramurphy** [comment]
I just signed the CLA.

@beckjake @drewbanin do I need to add anything to the tests for this? I saw several schema.yml files in the integration tests section but wasn't sure where this would best fit in.

**Comment by drewbanin** [comment]
Thanks for opening this PR @tayloramurphy! (@cla-bot check)

I just added a comment to [the discussion on naming this field](https://github.com/fishtown-analytics/dbt/issues/1362#issuecomment-567146810) in the issue. Let me know what you think about that suggestion in the issue thread.

I'll check out the code changes here. Kicking off the tests presently.

**Comment by tayloramurphy** [comment]
I see the failing tests - will work on updating.

**Comment by tayloramurphy** [comment]
@drewbanin pg integration tests are failing but it looks like it's on the install postgres step. I tried submitting another commit to see if it was a one-off but maybe there's something deeper? Please advise.

**Comment by drewbanin** [comment]
@tayloramurphy this is definitely weird - I see:
```
[NuGet] The operation has timed out
```

It looks like it's related to an incident over here: https://status.chocolatey.org/

I'll kick off these tests again when it looks like things have been resolved w/ chocolatey

**Comment by beckjake** [comment]
I saw this happen for a few days in a row with another PR, but could not repro on my Windows box. It mysteriously went away after a time - I guess chocolatey is having some problems.

**Comment by tayloramurphy** [comment]
I'll get back to this after the Christmas holiday!

**Comment by tayloramurphy** [comment]
@drewbanin looks like postgres integration tests are passing but AFAICT the BQ, Snowflake, and Redshift integration tests are failing b/c it can't connect. Is this still related to the chocolately outage? https://status.chocolatey.org/issues/2019-12-18-timeouts-when-searching-and-installing-packages/

**Comment by tayloramurphy** [comment]
Yes! Tests are passing! @drewbanin or @beckjake officially submitting for review 😄

**Comment by drewbanin** [comment]
Thanks @tayloramurphy! I gave this a quick functional test and it looks really good to me :)

I also just queued up this issue to render these eventual values in the docs site: https://github.com/fishtown-analytics/dbt-docs/issues/66

Nice work with the tests here - I know that updating node contracts in the test suite can be a real slog!

Adding @beckjake for code review

**Comment by drewbanin** [comment]
Just merged - thanks for your contribution to dbt @tayloramurphy :D

**Comment by tayloramurphy** [comment]
Thank you both for the review! I'm pumped to get this feature in 😄

**Pull request merged**
