### PR TITLE
Change redshift diststyle behavior

### LINKED ISSUE #2246: Don't provide a diststyle to redshift tables when diststyle is configured as "auto"
### Describe the bug
Redshift does not support explicitly setting a diststyle to `auto`. Instead, if a user configures a diststyle as "auto", dbt should ignore the config. This compels Redshift to use the "auto" diststyle.

See this thread for more info: https://github.com/fishtown-analytics/dbt/issues/1882

### Steps To Reproduce
```
-- models/my_model.sql

{{ config(materialized='table', dist='auto') }}

select 1 as id
```

The model will fail to build indicating that `auto` is not a valid diststyle.

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [x] redshift
- [ ] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
0.16.0
```

### PR DESCRIPTION
**Pull request by rodrigodelmonte**
resolves #2246

### Description
  * Don't provide a diststyle to redshift tables when configured as "auto"

### Checklist
 - [x] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
 - [x] I have run this code in development and it appears to resolve the stated issue
 - [x] This PR includes tests, or tests are not required/relevant for this PR
 - [x] I have updated the `CHANGELOG.md` and added information about my change to the "dbt next" section.

### CODE REVIEW

**Comment by drewbanin** [comment]
Thanks @rodrigodelmonte! This looks good to me -- i'll kick off the tests here :)

@cla-bot check

**Comment by rodrigodelmonte** [comment]
@drewbanin 
Thanks for the reminder, done!

**Comment by drewbanin** [comment]
Alright alright, thanks @rodrigodelmonte! It looks like there's a changelog merge conflict - do you mind if I fix that up for you real quick? I'm happy for you to do it as well, lmk if you'd like a hand at all. Going to ship this as soon as that conflict is addressed!

**Comment by rodrigodelmonte** [comment]
@drewbanin Let me know if it is fine now!

Should I have just one commit or can you squash the 2 commits ?

**Comment by drewbanin** [comment]
This is great as-is. I'm going to merge it presently. Thanks for contributing to dbt!

**Pull request merged**
