### PR TITLE
Add support for altering BigQuery column types

### LINKED ISSUE #2546: Implement BigQuery alter column type functionality
### Describe the feature
Currently dbt uses the default macro implementation for altering column types which doesn't actually work with BigQuery. This feature would implement a BigQuery specific macro that allows users to alter column types.

### Describe alternatives you've considered
BigQuery currently has two methods user's can use to alter a column type. The first method is done purely in SQL, the second involves uploading data to cloud storage. I believe the SQL specific approach makes more senes for dbt.

https://cloud.google.com/bigquery/docs/manually-changing-schemas#changing_a_columns_data_type

### Additional context
Feature is specific to BigQuery

### Who will this benefit?
BigQuery dbt users who might find themselves in need of a way to alter a column type through dbt.

### PR DESCRIPTION
**Pull request by azhard**
resolves #2546 

### Description

Implements functionality to alter BigQuery column types using dbt.

### Checklist
 - [x] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
 - [x] I have run this code in development and it appears to resolve the stated issue
 - [x] This PR includes tests, or tests are not required/relevant for this PR
 - [x] I have updated the `CHANGELOG.md` and added information about my change to the "dbt next" section.

### CODE REVIEW

**Comment by jtcohen6** [comment]
I just want to clarify my understanding of the implications: dbt only uses the `alter_column_type` method within the `expand_column_types` method, which is a noop on BigQuery. Out of curiosity, do you have a specific use case for this?

In any case, I agree with your rationale (in #2546) that:
* the default implementation doesn't work on BQ, so anything (even a compilation error) is better than the status quo
* without BQ having a _great_ way of implementing this, best to implement it in a SQL-first way

I'm a little uneasy that it requires replacing the entire table, but I guess that's the best of what they recommend. I'm still hopeful for support someday of `alter table ... remove column` (adding new type + removing old type is how we do this on other databases), or `alter table ... alter column set data type ...` (though this frequently has limitations when implemented).

**Comment by azhard** [comment]
Hey @jtcohen6, the reason I'm implementing this is because my team is planning to use dbt to handle some of our schema management and we have probably 90% of what we need already with the macros that currently exist. So considering there was an `alter_column_type` macro, figured it made sense to just implement it to actually work with BigQuery.

In terms of specific schema management use case, our dbt source tables get loaded through various mechanisms and schema changes get propagated through. These schema changes can then cause breaks in our downstream tables that are based on incremental loads. This doesn't mitigate that, but I've built a mini schema management tool that leverages dbt macros to allow us to fix / update schemas as needed. So for this particular macro, in the rare case where a data type got changed, we can use this macro to fix the downstream table's schema.

**Comment by jtcohen6** [comment]
Got it, that sounds reasonable—and cool that you're doing so much of it with dbt macros!

If someone's going to be calling this method from an external tool, I think it's fair to say they've read through the codebase around adapter methods. I'd be in favor of adding an inline code comment, _caveat usor_, that quotes or paraphrases from the BQ [docs](https://cloud.google.com/bigquery/docs/manually-changing-schemas#changing_a_columns_data_type):

> Changing a column's data type using a query requires you to scan the entire table. The query charges can be significant if the table is very large.

**Comment by azhard** [comment]
Just to make sure we're on the same page, is adding that as a jinja comment to the top of the macro what you had in mind?

**Comment by jtcohen6** [comment]
Yes, that's exactly what I had in mind—a quick note and link to that BQ docs page, within a Jinja comment, at the top of the `bigquery__alter_column_type` macro.

**Comment by azhard** [comment]
Hey @jtcohen6 any other changes needed?

**Comment by beckjake** [comment]
Looks like the redshift tests triggered a redshift bug, I'm just re-running that from failed. The postgres tests look like an issue I fixed a while ago, but this PR is pretty old so I assume it just hasn't pulled in the fix.

I'm perfectly comfortable merging this in as it is once the redshift test passes. Nothing this PR changes should care about the OS.

**Pull request merged**
