### PR TITLE
log 'depends_on_nodes' node attribute in the log record 'extra' field

### LINKED ISSUE #2316: Log test node metadata: depends_on_nodes
### Describe the feature
Currently the `extra` field from the structured log record is providing `unique_id` and `run_state` for test nodes. 
```json
{"timestamp": "2020-04-13T08:01:21.445113Z", "message": "10:01:21 | 2 of 385 START test assert_nnull_refid............................... [RUN]", "channel": "dbt", "level": 11, "levelname": "INFO", "thread_name": "Thread-6", "process": 13649, "extra": {"unique_id": "test.pmt_curated.assert_nnull_refid", "run_state": "running"}}
```
Include additional metadata field `depends_on_nodes` from the test node
```json
{"timestamp": "2020-04-13T08:01:21.445113Z", "message": "10:01:21 | 2 of 385 START test assert_nnull_refid............................... [RUN]", "channel": "dbt", "level": 11, "levelname": "INFO", "thread_name": "Thread-6", "process": 13649, "extra": {"unique_id": "test.pmt_curated.assert_nnull_refid", "run_state": "running", "depends_on_models": ["modelA", "modelB"]}}
```

### Who will this benefit?
People analyzing the logs for getting pipeline metrics can relate a failed test to a model or set of models.

Also [asked in in Slack](https://getdbt.slack.com/archives/C50NEBJGG/p1586535792024000).

### PR DESCRIPTION
**Pull request by dcereijodo**
resolves #2316 

### Description
Changed logger configuration to log `depends_on_nodes` node attribute when logging with the `ModelMetadata` context.

### Checklist
 - [x] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
 - [X] I have run this code in development and it appears to resolve the stated issue
 - [X] This PR includes tests, or tests are not required/relevant for this PR
 - [x] I have updated the `CHANGELOG.md` and added information about my change to the "dbt next" section.

### CODE REVIEW

**Comment by drewbanin** [comment]
Thanks for opening this issue @dcereijodo! Tagging @beckjake to review.

Before we get into a proper review though - do you mind resubmitting the CLA form? I see that the address entered into the form was only partially entered. We're going to need a complete mailing address in order to record the CLA submission to get this PR merged. Thanks for your help!

**Comment by dcereijodo** [comment]
Hey. I've updated the changelog accordingly.

I've also submitted again the CLA, but it seems that the bot complained again. It's just [this form](dcereijo@digitalorigin.com) a need to fill in and submit no?

I anyways tried one more time. You can let me know here or in Slack if it's still not working.

Captura de pantalla 2020-04-21 a las 8 28 42

**Comment by beckjake** [comment]
@dcereijodo Thank you! After you submit, there's a second manual step on our end - should be all set now.

**Comment by beckjake** [comment]
@cla-bot check

**Comment by drewbanin** [comment]
hey @dcereijodo - based on your comment here (https://github.com/fishtown-analytics/dbt/issues/2316#issuecomment-617573541) this PR should be ready to go, right? If so, are you able to fix the merge conflict in the changelog? Once that's addressed, I think we'll be ready to ship this as-is

**Comment by dcereijodo** [comment]
@drewbanin it should be fine now.
Thanks 😄!

**Pull request merged**
