### PR TITLE
Add state:modified and state:new selectors

### LINKED ISSUE #2641: Slim CI runs, via state comparison and deferred refs
## Slim CI: MVP

For 0.18.0, we want to prioritize making the following use case possible:
```
dbt run -m state:modified+ --defer --state prod-target/
```

What does this do?
1. `--state prod-target/`: Compare the current project against the manifest specified in the `--state` arg (#2465)
2. `state:modified+`: Select the set of model nodes that are not present in the state manifest, or differ from the same-named model nodes in state manifest, and their children
3. `--defer`: Compile any `ref()` in a selected model that points to a node _not_ in the selection group by using the state manifest, instead of the default (target-informed) namespace (#2527)
4. Run all selected models

In terms of the user-side setup required for the V1 of this, we expect:

1. **dbt Cloud** will have a behind-the-scenes mechanism to accept user input (`job_id`) and surface up-to-date artifacts, either:
    - to a relative path that is predictable, stable, and git-ignored (e.g. `.dbt-cloud/`)
    - to an absolute path that is encoded in an env var
2. In **Airflow/CircleCI/etc**, in the steps before running dbt, users write bash commands to grab the artifact files from wherever they are and copy them to wherever they need to be

The underlying constructs open a pandora's box of questions that we'll need to continue thinking through:
* Deferring `ref`s in ephemeral models? Is this a performance killer during compilation?
* How do we reflect "deferral" in dbt artifacts? The run results should reflect that the model selected from the "deferred" namespace. What should the manifest do?
* What about models that should never/always be deferred? We want to be wary of global flags to control behavior which users really want to control on a per-model basis (see: `--full-refresh`).
* Are there cases where someone wants to compare state against one manifest and defer references to a different one?
* Should dbt offer handy mechanisms to move artifacts around?

There's more thinking to do. We're not going to block a first version of this by worrying about all the cascading implications.

## Related art

As a selector (#2640):

```yml
selectors:
  - name: delta_plus
     definition:
       method: state   # this would return an error if `--state` is not passed
       value: modified
       children: true
```

As a workflow (#1842):

```yml
workflows:
  - name: slim_ci
    steps:
      # assuming the prod manifest is already in a folder called `prod-target`
      - name: run_changed
        description: Run changed models, parents, children
        command:
          subcommand: run
          selector: delta_plus
          defer: true
          state: 'prod-target'
      - name: good_tests
        description: Run my good tests
        command:
          subcommand: test
          selector: delta_plus
          on_error: continue
      - name: generate_docs
        description: Make my docs
        command:
          subcommand: docs generate
```

This is effectively a Makefile, with a few added benefits:
* Define dbt subcommands as dicts instead of CLI arg syntax
* Control `on_error` behavior: continue to next workflow step, or stop the workflow altogether

I feel good about adding this functionality, and the syntax above feels reasonable. The big unknowns are (a) how people will use these, and (b) how dbt Cloud could compellingly hook into these. If possible, I'd like to add _very_ initial support for workflows in 0.18.0 and leave it undocumented / call it out as liable to change.

### PR DESCRIPTION
**Pull request by beckjake**
resolves #2641 

### Description
Added `state:modified` and `state:new` selectors. All new nodes are modified nodes.

There are a few kinds of modifications:
 - names (database, schema, alias)
 - content (for seeds, a file checksum if <1mb or path if >=1mb. For tests, the test name + kwargs. For everything else, the raw sql of the node)
 - configuration (materialization, fqn, quoting, ...)
 - description fields, if persist_docs is set to persist the changed description

Tags configured via dbt_project.yml are not a change (doing it via `{{ config(...) }}`  is a raw_sql change, sadly).

Seed files larger than 1mb do not get compared.

There's probably room to be less fiddly about what's a change and what isn't!

If you pass a `state:modified` selector and dbt detects that any of your macros have changed, dbt logs a blanket warning once per selector to let the user know that `state:modified` won't see those changes. This warning is never an error (it goes directly through `logger.warning`, not `warn_or_error`).

Two small structural changes to dbt:
 - I moved the various things about files themselves into a new contracts module alongside the manifest contracts (where they used to live) as part of this. Now that checksums live on nodes, it caused an import cycle. Also, they never _really_ belonged in the manifest module.
 - I re-worked `main` to accept `--state` to commands that use selectors and merge some common logic on that front. This was inspired by making all these changes and then realizing I forgot to handle `ls` because it's totally separate... hopefully this is better.

This PR does bloat the manifest a little bit with checksums. It seemed hard to avoid, though technically we could change it so only seeds have them.

### Checklist
 - [X] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
 - [X] I have run this code in development and it appears to resolve the stated issue
 - [X] This PR includes tests, or tests are not required/relevant for this PR
 - [X] I have updated the `CHANGELOG.md` and added information about my change to the "dbt next" section.

### CODE REVIEW

**Comment by beckjake** [comment]
>I now think we should never consider database/schema/alias for marking nodes as modified, because these are high env-aware values that are likely to be different across environments. What do you think?

I think this would be fine, perhaps not intuitive. One thing we could look into is comparing the configured database/schema/alias values, before `target` has been considered (so they can be `None`). Would that be better? I'm not sure exactly how easy it is, but it sure feels like it should be easy! This wouldn't account for `generate_*_name` macros though.

>Vars
First of all, if we're considering vars, I think we should just not support v1 configs here. If you set `state:modified` and your config is v1, it's an error, can't do it. I don't want to think about it and support every silly edge case just for deprecated functionality.

We can do a vars check - as you've correctly identified, it's just like the macro dependencies issue. One issue we'll see is that we don't really have the vars in the manifest currently, so we'll have to include those. We'll have the same problem with `env_var` and I don't have a solution for taht: we can't dump the env, there's secrets in there!

**Comment by jtcohen6** [comment]
> This wouldn't account for `generate_*_name` macros though.

Use of these macros is pretty widespread, and hard to account for in its permutations. I feel strongly that we need state comparison to work for projects that override default database/schema/alias behavior in an env-based way, and I want to worry as little as possible about the ways in which they do it.

So I'm trying to think of a counterargument. What's the downside of completely ignoring changes to database/schema/alias in a CI environment? We already have good errors at compile time if dbt finds multiple resources with the same database representation.

I agree this would be less intuitive. It warrants an explanation in our docs.

What about for snapshots, where `target_database`+ `target_schema` tend to be stable across environments? I don't think it matters. It's not currently possible to `dbt snapshot --select state:modified`, and I don't see a use case for "only execute my modified snapshots," anyway.

> > Vars
* Totally agree with eschewing v1
* Sounds feasible for v2
* Env vars I don't care about. I see them in the same category as profile/target configs and database/schema/alias: these things _should_ be different across deployment + development environments, so diffing on them does not help. (I'm open to the argument that `vars` should fall into this category, too, but for now I don't think they do.)

**Comment by beckjake** [comment]
>What's the downside of completely ignoring changes to database/schema/alias in a CI environment?

Well, I imagine a world where you change a database name field or something and it ends up being queried by an external dashboard. Should `dbt run --models state:modified` pick that up? Maybe not, I actually don't have much intuition here.

**Comment by beckjake** [comment]
>I'm open to the argument that vars should fall into this category, too, but for now I don't think they do.

I have to think about this more, intuitively I think CLI vars are like env vars, but vars defined in your dbt_project.yml are like config items. That's not a very good answer though, because that's a pain to implement.

**Comment by jtcohen6** [comment]
> Well, I imagine a world where you change a database name field or something and it ends up being queried by an external dashboard.

It's a really good thought. I think that'd be a separate (and really cool) project, maybe plugging into existing thoughts on catalog comparison + having dbt know more about downstream model "exposures." Separate from running models in CI, I could imagine providing a warning in CI: "FYI you changed some columns in model X / the alias of model X, be aware that this may impact Y, Z downstream exposures that depend on it."

I'm good with punting on `vars` until v0.19.0.

**Comment by beckjake** [comment]
>I'm good with punting on vars until v0.19.0.

I would really like to do that, because then we can remove v1 config support before we do it. I think I will feel a lot better about this when calculating vars for a given model only requires its package. That's the kind of thing we can just cram into the manifest.

If we're going to say that database/schema/alias is no longer considered a change for nodes, should it be for sources?

**Comment by jtcohen6** [comment]
Sources are an excellent question. Changes to a source's database representation could indicate a meaningful modification, such as switching an ingestion mechanism, which is definitely worth testing downstream dependencies. By default, dbt expects sources to have the same database representations across environments. (Same as snapshots.)

That said, users can (and often do) override sources to be:
```yml
sources:
  - name: application_db
    schema: "{{ 'application_db_prod' if target.name == 'prod' else 'application_db_staging' }}"
```

The former, which is an "actual" modification, takes place quite rarely. The latter would be identified as a false positive _every single run_.  So while I don't feel great about it, I don't think we should compare source database/schema/identifier. That also keeps us consistent across node types.

Here are the more complex approaches I can imagine taking:
* If a source's database/schema/name/identifier is a Jinja expression, we _don't_ try to compare it; if it's a string literal, we _do_. This may not be possible, and it may be too confusing to be desirable, anyway.
* An eventual resolution (not for v0.18.0) is the ability to compare state against one manifest and defer to a different one. This would allow someone to `dbt compile --target ci`, have all the namespaces in that manifest be right _for comparison_, but then defer to another manifest with a different set of namespaces.

**Quoting** still feels like a change. Accidentally switching off quoting could definitely be a breaking change. Also, I would never expect quoting behavior to be different across environments. Even though this is tightly linked to database representation, it feels more like a model config in the vein of `materialized`, `sort`/`dist`, etc.

**Pull request merged**
