### PR TITLE
Add BigQuery option to define a maximum query cost limit

### LINKED ISSUE #2346: Add maximum_bytes_billed option for BigQuery
### Describe the feature
BigQuery has the query option maximum_bytes_billed, which sets a limit for the maximum acceptable cost for individual queries. Any query that exceeds this cost will automatically fail. It would be nice if one could use this feature in DBT to guard against potentially expensive mistakes.

I suggest adding this option in the profile settings, where one can already set the BigQuery query priority and other BigQuery specific settings.

Let me know if you would like to get a pull request for this. It is a small change and I'd be happy to implement it.

### Describe alternatives you've considered
I have researched ways to try and set this option via environment variables or ~/.bigqueryrc. While one can set the option in bigqueryrc, that does not influence the BigQuery client SDK, only the BigQuery commandline tools (which does not help for DBT).

### Additional context
This is BigQuery specific.

### Who will this benefit?
Consider a table with a million rows that you join with another table with a million rows. You mess up the join condition and accidentally create a full cross join. Since BigQuery has huge scaling capabilities, it will happily create the resulting table with 10^11 rows. Any scan of that table will be hugely expensive. This option would protect against such mistakes.

### PR DESCRIPTION
**Pull request by haukeduden**
resolves #2346

### Description

This adds the option maximum_bytes_billed to BigQuery profiles. When this is set and not 0 then the corresponding query job option will be set. This is analogous to specifying `bq query --maximum_bytes_billed` on the commandline.

### Checklist
 - [X] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
 - [X] I have run this code in development and it appears to resolve the stated issue
 - [X] This PR includes tests, or tests are not required/relevant for this PR
 - [X] I have updated the `CHANGELOG.md` and added information about my change to the "dbt next" section.

### CODE REVIEW

**Comment by haukeduden** [comment]
@drewbanin I signed the CLA, specifying my user name "haukeduden". I got the message "Your response has been recorded.", so I assume that it has worked. But the CLA verification still seems to fail.

**Comment by beckjake** [comment]
@cla-bot check

**Comment by beckjake** [comment]
@haukeduden our cla-bot stuff requires manual intervention, unfortunately. This looks good to me, though flake8 seems upset about some things based on the failing tests. Please also add yourself to the changelog under "contributors" (just make a new section for the next release if there isn't one) so we can give you credit in the release notes!

**Comment by haukeduden** [comment]
@drewbanin I added the entry to contributors, as you asked, and fixed a whitespace issue that flake8 complained about. Sorry for not catching this before submitting. flake8 still fails, though -- but it complains about issues in files that have not been updated (`E741 ambiguous variable name 'l'`in core/dbt/utils.py, core/dbt/rpc/task_handler.py and core/dbt/rpc/builtins.py).
Apparently this issue was already present in the base branch when I branched off.
It seems to me that this should be fixed in a separate PR, since it has nothing to do with the new BigQuery feature. Do you agree?

**Comment by beckjake** [comment]
@haukeduden totally! I think if you pull in `dev/octavius-catto` again, drew merged a change that will suppress that error.

**Comment by haukeduden** [comment]
@beckjake I pulled the latest changes and that fixed the problem 👍. The tests pass now.

**Comment by drewbanin** [comment]
Merged! Thanks for your contribution @haukeduden -- this will ship in 0.17.0 :D

**Pull request merged**
