### PR TITLE
set default `materialized` for test node configs

### LINKED ISSUE #2806: dbt test [--models|--exclude] config.materialized:view does not seem to work
### Describe the bug
I tried to run `dbt test --exclude config.materialized:view`, and got the output "Nothing to do". I then tried to run `dbt test --models config.materialized:view`, and all tests ran. Yet `dbt test --models config.materialized:table` runs only 24 models.

### Steps To Reproduce
In a project that has models materialized as a view and others materialized as a table / or `'incremental'` ones, run `dbt test --exclude config.materialized:view`, or `dbt test --models config.materialized:view`.

### Expected behavior
`dbt test --exclude config.materialized:view` should run all models that are not materialized as a view.

`dbt test --models config.materialized:view` should run only models materialized as a view.

### Screenshots and log output
```
$ dbt test --exclude config.materialized:view
Running with dbt=0.18.0
* Deprecation Warning: dbt v0.17.0 introduces a new config format for the
dbt_project.yml file. Support for the existing version 1 format will be removed
in a future release of dbt. The following packages are currently configured with
config version 1:
 - dbt_utils
 - redshift

For upgrading instructions, consult the documentation:
  https://docs.getdbt.com/docs/guides/migration-guide/upgrading-to-0-17-0

* Deprecation Warning: The "adapter_macro" macro has been deprecated. Instead,
use the `adapter.dispatch` method to find a macro and call the result.
adapter_macro was called for: dbt_utils.type_string
Found 198 models, 295 tests, 0 snapshots, 0 analyses, 340 macros, 0 operations, 3 seed files, 0 sources
WARNING: Nothing to do. Try checking your model configs and model specification args
```

Then:

```
$ dbt test --models config.materialized:view
Running with dbt=0.18.0
* Deprecation Warning: dbt v0.17.0 introduces a new config format for the
dbt_project.yml file. Support for the existing version 1 format will be removed
in a future release of dbt. The following packages are currently configured with
config version 1:
 - dbt_utils
 - redshift

For upgrading instructions, consult the documentation:
  https://docs.getdbt.com/docs/guides/migration-guide/upgrading-to-0-17-0

* Deprecation Warning: The "adapter_macro" macro has been deprecated. Instead,
use the `adapter.dispatch` method to find a macro and call the result.
adapter_macro was called for: dbt_utils.type_string
Found 198 models, 295 tests, 0 snapshots, 0 analyses, 340 macros, 0 operations, 3 seed files, 0 sources
14:48:36 | Concurrency: 4 threads (target='staging_dev')
14:48:36 |
14:48:36 | 1 of 295 START test not_null_account_attributes_d_uuid............... [RUN]
...
```

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [x] redshift
- [ ] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
installed version: 0.18.0
   latest version: 0.18.0

Up to date!

Plugins:
  - bigquery: 0.18.0
  - snowflake: 0.18.0
  - redshift: 0.18.0
  - postgres: 0.18.0
```

**The operating system you're using:**
OSX

**The output of `python --version`:**
Python 3.6.8

### PR DESCRIPTION
**Pull request by kwigley**
(possibly) resolves #2806 

### Description

After noticing similar behavior for seed and snapshot node configs, this change sets the default `materialized` for test node configs to `test`. It aligns selection behavior, but this is definitely extending the meaning of `materialized`.

### Checklist
 - [x] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
 - [x] I have run this code in development and it appears to resolve the stated issue
 - [x] This PR includes tests, or tests are not required/relevant for this PR
 - [x] I have updated the `CHANGELOG.md` and added information about my change to the "dbt next" section.

### CODE REVIEW

**Comment by gshank** [comment]
Looks like a great easy win!

**Comment by rsella** [comment]
Just adding my two cents here, feel free to ignore if I missed something in the big picture.

In my opinion materialized = test can make great sense for data tests, even if it means extending the "formal" materialized meaning (as noted by @kwigley )

For schema test I personally think that materialized should be set to the model materialization.
So for example if the model has incremental, it should be incremental, if model has view it should be view, and so on

I can see two main benefits:
1. Selecting models with a filter on materialization (config.materialized: view|table|...) will actually also select the related schema tests. Using the materialized = test, I guess we will lose a flexible way of selecting things
2.  While I can get a sense of "materialization" for data test, I fail to see a meaning in materialization for schema tests (what is materialization for a IS NOT NULL check?).
In my idea the materialization for schema test will be then intended as a "copy" of the parent (target) model


I don't know if it is possible to do so, I don't have enough knowledge of the codebase


What do you think?

**Comment by jtcohen6** [comment]
@rsella Appreciate you weighing in! A lot of our thinking for the release after the next is around tests: how can we rationalize them, make them a bit more fully-featured, and reconcile confusing differences between data tests and schema tests.

Per the proposal in #2593, we want a bit more heft to tests such that they can wrap SQL (either from data test file or schema test macro), apply a common set of configs (severity, limit), calculate the number of failures, _and optionally_ write those failing results to a table. This PR has helped me realize that the right wrapper may in fact be a formal Jinja materialization, named `test`, which could then be reimplemented on different adapters and in users' own projects as needed.

> Selecting models with a filter on materialization (config.materialized: view|table|...) will actually also select the related schema tests. Using the materialized = test, I guess we will lose a flexible way of selecting things

This already works, based on the way that test selection works today—`dbt test` takes account of properties of parent models when identifying tests. The specific bug we're trying to resolve here is:
`dbt test -m config.materialized:table` = run tests that select from `table`-materialized models
`dbt test -m config.materialized:view` = run _all_ tests (because every test has the default value of `materialized: 'view'`)

With this code change:
`dbt test -m config.materialized:table` = run tests that select from `table`-materialized models
`dbt test -m config.materialized:view` = run tests that select from `view`-materialized models
`dbt test -m config.materialized:test` = run all tests

**Comment by rsella** [comment]
@jtcohen6 all clear, seems like the materialized = test proposal is perfect then

Thanks for the explanation btw

**Review by jtcohen6 — APPROVED** [review]
let's do it

**Review by gshank — APPROVED** [review]

**Pull request merged**
