### PR TITLE
Improve Error Messaging for Invalid Source Arguments

### LINKED ISSUE #1660: Better error messaging for malformed source/ref inputs
## Feature

Catch malformed inputs to `source()` and `ref()` functions and elegantly bubble up to end user.

### Current error messaging is non-obvious

had a colleague who is new to dbt encounter the following cryptic error today:
```
__call__() missing 1 required positional argument: ‘table_name’
```
my hunch, knowing a good amount about dbt, was that this was related to a malformed `source()` call, was correct, as he only passed one arg into that fn instead of two:
```
{{ source('some_table') }}
vs
{{ source('my_schema', 'some_table') }}
```
even with the `--debug` flag, this was difficult to track down

### Request

It seems like these sorts of errors could be caught and communicated more effectively (I can't imagine my colleague is the first or last one to make this mistake), to output something like:
```
ERROR: source() function requires two arguments, but received only one
    in models/my_model/some_table.sql (line 51)
    >>>   from {{ source('my_table') }}
```

### Who will this benefit?

This will benefit any user who mistakenly leaves out a schema designation in her `source()` usage, or mistakenly includes a schema designation in a `ref()` call.

### PR DESCRIPTION
**Pull request by captainEli**
This pull request fixes #1660

This pull request enforces that exactly two arguments are provided to `source()` during compilation. If anything other than 2 arguments are given, a compiler error is now raised. This is an improvement over the current state described in #1660, where the error messaging is unclear after providing a single argument to `source()`.

#1660 also mentions adding better error messaging in `ref()` but it already seems satisfactory to me: https://github.com/fishtown-analytics/dbt/blob/dev/louisa-may-alcott/core/dbt/context/parser.py#L98-L107

This is my first contribution to dbt so I will need help with the CI environment variables.

Thanks to @emilieschario for helping me with this.

### CODE REVIEW

**Comment by drewbanin** [comment]
awesome, this looks great @captainEli!!

Are you able to sign the attached CLA? If so, we can definitely merge this for 0.15.0 :D

**Comment by drewbanin** [comment]
This looks pretty good to me -- going to kick off the CI suite now, but I think we'll me ready to merge this when the tests pass :)

Screen Shot 2019-10-07 at 5 41 55 PM

@cla-bot check

**Comment by emilieschario** [comment]
Great work @captainEli!!

**Comment by drewbanin** [comment]
ack - there's just one pep8 issue here:
```
core/dbt/context/parser.py:118:80: E501 line too long (84 > 79 characters)
```

If you're able to make that line <= 79 characters, then we should be ready to go here :)

**Comment by captainEli** [comment]
@drewbanin thanks for the help. I've shortened it now 👍

**Pull request merged**
