### PR TITLE
Feature to add _n alias to same column names #3147

### LINKED ISSUE #3147: Sql commands with same column name to dbt rpc produce weird results in table
### Describe the bug
When we run sql like `select 1 as a, 2 as b, 3 as a, 4 as d` produces weird table results as shown in screenshot below. 
Screen Shot 2021-03-04 at 10 26 08 PM

### Steps To Reproduce
1. Start dbt rpc server with `dbt rpc`.
2. Send curl to create a request in rpc server
```
 curl -X POST --header "Content-Type: application/json" "http://localhost:8580/jsonrpc" --data '{"jsonrpc": "2.0", "id": "1_1_2021-03-04T22:28:34.621-05:00", "method": "run_sql", "params": {"sql": "c2VsZWN0IDEgYXMgYSwgMiBhcyBiLCAzIGFzIGEsIDQgYXMgZApsaW1pdCA1MDAKLyogbGltaXQgYWRkZWQgYXV0b21hdGljYWxseSBieSBkYnQgY2xvdWQgKi8=", "name": "request", "task_tags": {"uriValue": "file:///1614005139931/__unsaved/Statement 1.sql", "clientStart": "2021-03-04T22:28:34.597-05:00", "branch_name": "master", "cli": "run_sql", "entityId": "ac36a481-aa3e-4503-96d3-c0ccbb2a5dbb"}}}'
```
3. Run curl to see output of above query request:
```
curl  -X POST --header "Content-Type: application/json" "http://localhost:8580/jsonrpc" --data '{"jsonrpc": "2.0", "id": "1_1_2021-03-04T22:28:34.621-05:00", "method": "poll", "params": {"request_token": "a76096de-a72b-4bd8-ba9e-8d70efd65237", "logs": true, "logs_start": 0}}'
```
Result looks something like below and we are looking for `table` key
```
{
   "result":{
      "state":"success",
      "start":"2021-03-05T04:16:02.795158Z",
      "end":"2021-03-05T04:16:04.445599Z",
      "elapsed":1.650441,
      "logs":[
         ....
            "table":{
               "column_names":[
                  "a",
                  "b",
                  "a_2",
                  "d"
               ],
               "rows":[
                  [
                     3.0,
                     2.0,
                     4.0,
                     null
                  ]
               ]
            }
         }
      ],
      "generated_at":"2021-03-05T04:16:04.232967Z",
      "elapsed_time":0.134774
   },
   "id":"1_1_2021-03-04T22:28:34.621-05:00",
   "jsonrpc":"2.0"
}
```

### Expected behavior
Result should've been:
```python
...
'column_names': ['a', 'b', 'a_2', 'd']
'rows': [[1.0, 2.0, 3.0, 4.0]]
...
```
### Screenshots and log output
Output of dbt rpc:
Screen Shot 2021-03-04 at 10 26 08 PM

### System information
**Which database are you using dbt with?**
- [x] postgres
- [ ] redshift
- [ ] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
installed version: 0.17.0
   latest version: 0.19.0

Your version of dbt is out of date! You can find instructions for upgrading here:
https://docs.getdbt.com/docs/installation

Plugins:
  - bigquery: 0.17.0
  - snowflake: 0.17.0
  - redshift: 0.17.0
  - postgres: 0.17.0
```

**The operating system you're using:**
macOS Catalina 10.15.7

**The output of `python --version`:**
Python 3.7.4

### PR DESCRIPTION
**Pull request by techytushar**
Signed-off-by: Tushar Mittal <chiragmittal.mittal@gmail.com>

resolves #3147 

### Checklist
 - [x] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
 - [ ] I have run this code in development and it appears to resolve the stated issue
 - [ ] This PR includes tests, or tests are not required/relevant for this PR
 - [x] I have updated the `CHANGELOG.md` and added information about my change to the "dbt next" section.

### CODE REVIEW

**Review by jtcohen6 — COMMENTED** [review]
Thanks for picking this up @techytushar, this is awesome! I took this for a spin locally, and it resolves both of the reproduction cases mentioned in #3147 (calling `run_query()` in a file, and the original RPC request).

- Could you add a test? I think a unit test is sufficient, passing multiple columns with the same name to `process_results()` and checking that all columns are present before and after.
- Could you add yourself to the list of contributors?

I'll also tag one of the folks from the Core team for python review. In particular, I'd like to know if a loop-based approach would have meaningful performance implications at scale.

**Comment by gshank** [comment]
I think the performance implications are trivial, and the fix looks good to me.

**Review by gshank — APPROVED** [review]

**Comment by techytushar** [comment]
Hi @jtcohen6 , thank you for the review. In the unit tests folder there are lot of files, please can you tell in which one should I add the test? Also I am unable to find the list of contributors, can you guide me in this as well 🙂

**Comment by jtcohen6** [comment]
@techytushar Good call! It doesn't look like any of the existing unit test files have related coverage, so I think a new unit test file makes sense—something like `unit/test_sql_result.py`. Here's what I'm envisioning as the basic setup:
```python
import unittest
from dbt.adapters.sql.connections import SQLConnectionManager

class TestProcessSQLResult(unittest.TestCase):
    def test_duplicated_columns(self):
        cols_with_one_dupe = ['a', 'b', 'a', 'd']
        rows = [(1, 2, 3, 4)]

        self.assertEqual(
            SQLConnectionManager.process_results(cols_with_dupe, rows),
            [{"a": 1, "b": 2, "a_2": 3, "d": 4}]
        )
        
        cols_with_more_dupes = ['a', 'a', 'a']
        
        ... more test cases ...
```

There's also a code style error from `flake8`, once fixed the rest of the CI suite will run:
```
core/dbt/adapters/sql/connections.py:107:80: E501 line too long (81 > 79 characters)
```

The Contributors section is just a few lines further down in the Changelog [here](https://github.com/fishtown-analytics/dbt/pull/3158/files#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4edR20).

Let me know if you have more questions, happy to help!

**Review by kwigley — APPROVED** [review]
looks good 👍 thanks for the contribution

**Review by jtcohen6 — APPROVED** [review]
Thanks for this @techytushar!

**Pull request merged**
