### PR TITLE
Dbt compile all sql

### PR DESCRIPTION
**Pull request by ronnyli**
https://github.com/fishtown-analytics/dbt/issues/588

### CODE REVIEW

**Comment by drewbanin** [comment]
@ronnyli I've taken a look at this a couple of times over the past week. It doesn't look like there's a super immediate path from where dbt is right now, to a version where all of the SQL is compiled. Let me take another stab at it this weekend. Alright if I get some groundwork code working, then send it your way for? Hopefully then you can take that code and run with it!

**Comment by ronnyli** [comment]
That'll help a lot Drew, thanks.

**Comment by ronnyli** [comment]
Hm yeah I'm pretty stumped, haha. So far all the logging changes I've made only log the `CREATE TABLE dbt_audit` hooks but not the hooks defined within the model file. Very bizarre.

**Comment by ronnyli** [comment]
On vacation over the next 4 weeks so I'll be out of reach. Looking forward to getting back to this afterwards though!

**Comment by drewbanin** [comment]
@ronnyli ok! we moved this issue into a milestone for an upcoming dbt release, so we'll definitely be working on it soon. I'll be really happy when this is working :)

**Comment by cmcarthur** [comment]
@drewbanin what's the status of this

**Comment by drewbanin** [comment]
@ronnyli I'm going to close this since dbt has changed a whole bunch since you wrote this code initially. I'm definitely _very_ keen to do this, but it requires a bunch of significant code changes to dbt. Feel free to re-open this if you plan on making more headway, otherwise, let's further flesh out implementation details in the issue!

**Pull request closed without merging**
