### PR TITLE
Dockerfile with utility entrypoint

### PR DESCRIPTION
**Pull request by igrayson**

### CODE REVIEW

**Comment by drewbanin** [comment]
hey @igrayson -- thanks for submitting this! @cmcarthur is the resident Docker expert here, so I'll let him take a look

**Comment by igrayson** [comment]
Yep: https://gist.github.com/anonymous/a5042d680c39e288c08a22a929ceb73f

**Comment by igrayson** [comment]
It looks like `alpine-python` was updated 2 weeks ago to use alpine linux 3.6; I'm probably building with an older version. Boo on them for overwriting tags.

**Comment by igrayson** [comment]
I'm leaning towards just putting the python setup commands directly in this Dockerfile, so we don't have to rely on any base image less official than the actual alpine docker image.

**Comment by drewbanin** [comment]
Closing this -- a dbt Dockerfile can be found [here](https://github.com/fishtown-analytics/dbt/blob/development/Dockerfile)

We'll write some docs for how to do this: https://github.com/fishtown-analytics/dbt/issues/633

**Pull request closed without merging**
