### PR TITLE
fix the ambiguous alias exception to respect databases

### LINKED ISSUE #2326: Ambiguous alias exception should check `database` config
### Describe the bug
dbt's [`raise_ambiguous_alias`](https://github.com/fishtown-analytics/dbt/blob/dev/octavius-catto/core/dbt/exceptions.py#L711) exception only takes into account a node's `schema` and `alias` when searching for collisions. It should also take into account a node's custom `database`.

### Steps To Reproduce
1. Create two models with different file names and `database` configs, but the same `schema` and `alias` configs. E.g.:
```
{{
    config(
        materialized = 'table',
        database = 'analytics',
        schema = 'dbt_jcohen',
        alias = 'fct_sprints'
    )
}}
```
```
{{
    config(
        materialized = 'table',
        database = 'not_analytics',
        schema = 'dbt_jcohen',
        alias = 'fct_sprints'
    )
}}
```

2. Run `dbt compile`

```
Encountered an error:
Compilation Error
  dbt found two resources with the database representation "dbt_jcohen.fct_sprints".
  dbt cannot create two resources with identical database representations. To fix this,
  change the "schema" or "alias" configuration of one of these resources:
  - model.fishtown_internal_analytics.fct_sprintssss (models/marts/consulting/fct_sprintssss.sql)
  - model.fishtown_internal_analytics.fct_sprints (models/marts/consulting/fct_sprints.sql)
```

### Expected behavior

dbt's `raise_ambiguous_alias` method should take into account custom databases to determine if two models have identical database representations.

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [x] snowflake
- [ ] other (specify: ____________)

I have tested on Snowflake. I imagine it could be relevant on BigQuery as well.

**The output of `dbt --version`:**
```
installed version: 0.16.1
   latest version: 0.16.1

Up to date!
```

### PR DESCRIPTION
**Pull request by beckjake**
resolves #2326 

### Description
Fixes the ambiguous alias exception so now it respects databases

- The alias name check is now tied to the behavior of adapter.Relation.create_from(...)
- Plugins that override the `include` of their relations will use whatever they render to for the check the actual exception-raising code gets the name that was compared instead of generating its own
- Finally, I added a reasonable fallback behavior since this method _was_ exposed to the context

### Checklist
 - [X] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
 - [X] I have run this code in development and it appears to resolve the stated issue
 - [X] This PR includes tests, or tests are not required/relevant for this PR
 - [X] I have updated the `CHANGELOG.md` and added information about my change to the "dbt next" section.

### CODE REVIEW

**Comment by beckjake** [comment]
Merging this before tests - just a changelog update

**Comment by azhard** [comment]
This feature is currently blocking my team from launching dbt as we have multiple BigQuery biews with the same view name & dataset name but different project. 

Just curious about rough timeline for when this will be released in a new version of dbt?

**Comment by drewbanin** [comment]
hi @azhard - this change will go out in our next release, dbt v0.17.0. We'll be cutting the first pre-release today, and the final release will be live at the end of the pre-release period (as soon as two weeks from now, but the exact date depends on how testing goes).

**Comment by azhard** [comment]
That's awesome - thanks for the quick reply @drewbanin, really appreciate it!

**Pull request merged**
