### PR TITLE
Remove unconditional calls to get_latest_version (#907)

### PR DESCRIPTION
**Pull request by beckjake**
I'm pretty sure that it really is this easy.

### CODE REVIEW

**Comment by beckjake** [comment]
@drewbanin ok, this is actually fixed now, you can see the tricky bit...

**Comment by drewbanin** [comment]
@beckjake I just tried running this locally and saw:
```
$ dbt --version
usage: dbt: data build tool [-h] [--version] [-d] [-S]
                            {init,clean,debug,deps,archive,run,compile,docs,seed,test}
                            ...
dbt: data build tool: error: too few arguments
```

**Comment by beckjake** [comment]
@drewbanin that's really weird, on my machine I get:
```
$ dbt --version
installed version: 0.11.0-a1
   latest version: 0.10.2

Your version of dbt is ahead of the latest release!
```

**Comment by drewbanin** [comment]
LGTM (again) when the tests pass!

**Pull request merged**
