### PR TITLE
Wider google-cloud dependencies

### LINKED ISSUE #2794: [BigQuery] Allow more recent versions of google-api-core?
### Describe the feature

Currently dbt-bigquery has [an upper limit of 1.16 on `google-api-core`](https://github.com/fishtown-analytics/dbt/blob/v0.18.1b3/plugins/bigquery/setup.py#L53). That release is from Jan of this year.

Would it be possible to loosen that?

While it's clearly not dbt's responsibility for us to be able to install arbitrary packages, here's an example where we can't instally `google-cloud-bigquery-datatransfer` because of this restriction:

```
[SolverProblemError]
Because no versions of google-cloud-bigquery-datatransfer match >2.0.0,<3.0.0
 and google-cloud-bigquery-datatransfer (2.0.0) depends on google-api-core (>=1.22.2,<2.0.0dev), google-cloud-bigquery-datatransfer (>=2.0.0,<3.0.0) requires google-api-core (>=1.22.2,<2.0.0dev).
And because dbt-bigquery (0.18.0) depends on google-api-core (>=1.16.0,<1.17.0), google-cloud-bigquery-datatransfer (>=2.0.0,<3.0.0) is incompatible with dbt-bigquery (0.18.0).
And because dbt (0.18.0) depends on dbt-bigquery (0.18.0)
 and no versions of dbt match >0.18.0,<0.19.0, google-cloud-bigquery-datatransfer (>=2.0.0,<3.0.0) is incompatible with dbt (>=0.18.0,<0.19.0).
So, because {repo} depends on both dbt (^0.18.0) and google-cloud-bigquery-datatransfer (^2.0.0), version solving failed.
```

Thanks as ever for the awesome product!

### PR DESCRIPTION
**Pull request by max-sixty**
resolves #2794 

### Description

As discussed in the issue. I can narrow the range of these as per that issue; figured I'd ensure tests pass before fixing the versions.

### Checklist
 - [ ] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
 - [ ] I have run this code in development and it appears to resolve the stated issue
 - [x] This PR includes tests, or tests are not required/relevant for this PR
 - [ ] I have updated the `CHANGELOG.md` and added information about my change to the "dbt next" section.

### CODE REVIEW

**Comment by max-sixty** [comment]
Re CLA — I will get back to you on that, though not immediately

**Comment by max-sixty** [comment]
Are there docs on how to run integration tests in CircleCI? 

I've created a dummy project and put the service account json in the `BIGQUERY_SERVICE_ACCOUNT_JSON`, but I'm now getting `BIGQUERY_TEST_ALT_DATABASE` errors. The only reference I can see is in `test.env` which is gitignore-d

**Comment by jtcohen6** [comment]
Hey @max-sixty, thanks for contributing!
- It looks like tests for this are running in your "max-sixty" CircleCI org. Is that tied to your GitHub account? Normally, tests on all PRs (including forks) automatically run in the Fishtown CircleCi org, with all the right env vars. Check out [this comment](https://github.com/fishtown-analytics/dbt/pull/2741#issuecomment-691209577) for a workaround.
- What's your timeline for signing the CLA? This is a change I'd like to include in the next release, which should be a matter of weeks

**Comment by max-sixty** [comment]
Great — looks like disabling my CircleCI works, and it's now building under the main project's: https://app.circleci.com/pipelines/github/fishtown-analytics/dbt/1511/workflows/36fbd065-613e-4409-86f5-cf6092f232ef/jobs/33037

I'm not sure re CLA — I've escalated internally

**Comment by max-sixty** [comment]
Looks like tests pass!

Shall I pin the upper end of the Google Cloud dependencies to the currently release "minor" version (i.e. `major.minor.patch`)? 

While semver should allow us to pin to the current major version, as @drewbanin states, Google has let some breaking changes into minor versions: 

> We probably _do not_ want to set the upper bound to `<2.0.0` because breaking changes in libraries like this one can (and do) break older versions of dbt down the line.

The alternative would be something like what we do in [xarray](https://github.com/pydata/xarray/blob/cc271e61077c543e0f3b1a06ad5e905ea2c91617/azure-pipelines.yml#L28-L30), where we always test on the latest version of dependencies, and then fix any issues as they arise.

**Comment by max-sixty** [comment]
So we can test this on our workflows; let me know if you know off hand how to install this with pip — how can we get pip to view the `dbt-bigquery` dependency as the bigquery plugin inside this repo rather than the bigquery plugin in PyPI?

**Comment by max-sixty** [comment]
This is my current version for testing out this — it would be great to have a cleaner way of including updated dependencies, but not sure how to navigate pip / setuptools into allowing it from a subpackage, given they're currently defined as separate packages rather than sub-packages: https://github.com/max-sixty/dbt/compare/unlock-google-api...max-sixty:unlock-google-api-deps

**Comment by max-sixty** [comment]
Unfortunately I now get an error when running `dbt debug`. What's the standard way of testing out changes in plugins?

```
Configuration:
  profiles.yml file [ERROR invalid]
  dbt_project.yml file [OK found and valid]

Profile loading failed for the following reason:
Runtime Error
  Credentials in profile "{foo}", target "user" invalid: Runtime Error
    Could not find adapter type bigquery!
```

**Comment by jtcohen6** [comment]
Hey @max-sixty, thanks for the quick work here, and sorry for the delayed response —

> While semver should allow us to pin to the current major version, as @drewbanin states, Google has let some breaking changes into minor versions:

>> We probably do not want to set the upper bound to <2.0.0 because breaking changes in libraries like this one can (and do) break older versions of dbt down the line.

I'd rather stick to Drew's original rationale and be defensive here. I'm happy with testing against the latest stable minor version—I'd say that's `1.22.4` `google-api-core`, since `1.23.0` was just released a few weeks ago—but we should then set an upper bound against the next minor version (`<1.23.0`).

> how can we get pip to view the `dbt-bigquery` dependency as the bigquery plugin inside this repo rather than the bigquery plugin in PyPI?

My thought would be to either:
- Install from `pip install https://github.com/max-sixty/dbt/archive/unlock-google-api-deps.zip`
- Mock the local development process: clone the repository and `pip install -r editable_requirements.txt`

**Comment by max-sixty** [comment]
> My thought would be to either:
> 
>     * Install from `pip install https://github.com/max-sixty/dbt/archive/unlock-google-api-deps.zip`
> 
>     * Mock the local development process: clone the repository and `pip install -r editable_requirements.txt`

Right — I think the latter isn't possible to specify to pip / poetry — it would require manually downloading and installing. 
I'll continue doing the first — I'm sure you have good reasons for organizing the repo this way — though it does make this sort of testing harder.

I also couldn't seem to use `dbt-utils` because the version number was 0.19 — so I reset the version number back to 0.18.1. Let me know if I'm making a mistake there

**Comment by max-sixty** [comment]
> I'd rather stick to Drew's original rationale and be defensive here. I'm happy with testing against the latest stable minor version—I'd say that's `1.22.4` `google-api-core`, since `1.23.0` was just released a few weeks ago—but we should then set an upper bound against the next minor version (`<1.23.0`).

Done — I think you meant `<1.24.0`, lmk if not

**Comment by jtcohen6** [comment]
> I also couldn't seem to use dbt-utils because the version number was 0.19 — so I reset the version number back to 0.18.1. Let me know if I'm making a mistake there

That's a defensive upper bound in dbt-utils, in case the next minor dbt version has breaking changes. You can use the [`--no-version-check`](https://docs.getdbt.com/reference/project-configs/require-dbt-version/#disabling-version-checks) flag for this.

> Done — I think you meant `<1.24.0`, lmk if not

I was thinking we'd stick to `<1.23.0` since `1.23.0` just came out, but I don't really have strong feelings either way. `<1.24.0` is fine if the tests pass.

**Comment by max-sixty** [comment]
> That's a defensive upper bound in dbt-utils, in case the next minor dbt version has breaking changes. You can use the [`--no-version-check`](https://docs.getdbt.com/reference/project-configs/require-dbt-version/#disabling-version-checks) flag for this.

Great, thanks

**Comment by max-sixty** [comment]
I think I have now signed the CLA — does this not show up @drewbanin ?

**Comment by jtcohen6** [comment]
@cla-bot check

**Comment by jtcohen6** [comment]
@max-sixty Thanks for the CLA follow-up. Could you add a changelog note under v0.19.0 + add yourself to the list of contributors there? Then I think this is good to ship

**Comment by max-sixty** [comment]
Done!

**Comment by jtcohen6** [comment]
@max-sixty thanks for the contribution!

**Review by jtcohen6 — APPROVED** [review]

**Pull request merged**
