### PR TITLE
Fix casing comparisons on dbt-created relations (#1555)

### LINKED ISSUE #1555: Compilation error when searching for a relation
## Issue
Compilation error when searching for a relation

### Issue description

I have been using `get_relation` to determine if the relation exists in the schema or not. However, I am getting a run-time error (described as compilation error). 

Command: `dbt run --models address_xf`

Here's a code snippet of `address_xf`
```
{%- set source_relation = adapter.get_relation(
      database= target.database,
      schema= target.schema,
      identifier='address') -%}

{% if source_relation is none %}
    {% set address_columns_list = [] %}
{% else %}
    {% set address_columns_list = adapter.get_columns_in_relation(source_relation) -%}
{% endif %}
```

quoting  config in `dbt_project.yml`
```
quoting:
    identifier: false
    schema: false
```

### Results
I got a compilation error: 
```
Compilation Error in model “address_xf” 
  When searching for a relation, dbt found an approximate match. Instead of guessing
  which relation to use, dbt will move on. Please delete database.schema.model, or rename it to be less ambiguous.
  Searched for: DATABASE.SCHEMA.ADDRESS
  Found: database.schema.address
```

### System information
The output of `dbt --version`:
```
0.13.0
```

The operating system you're running on:
```
macOS Mojave
version 10.14.5
```

The python version you're using (probably the output of `python --version`)
```
Python 2.7.15
```
### Steps to reproduce

1. Create a base model but do not add this model to the schema 
2. Use `get_relation` for base_model in the transformed model (as described above)
3. `dbt clean -> dbt deps -> dbt seed -> dbt compile -> dbt run --models my_models`

**Additional notes:** 
- All the base and transformed models are materialized as views. 
- This mainly happens only when the transformed models are created for the first time in an existing or a new schema. If the base models are created/updated prior to using adapters in transformed models, there are no run-time errors. 
- The subsequent runs don't reproduce these run-time errors 
- I tried to change the case of `database/schema/identifier` using `|upper/ |lower`, however, it did return the same compilation error.

### LINKED ISSUE #1557: Models with upper case or mixed case names fail in consecutive runs
### Issue description
When running (`dbt run`) the model with an uppercase name (or name containing upper case characters), the first run succeeds, but the consecutive run fails.

### Results
I expected my models to either be executed successfully also when re-running them, or if using upper case model names is not supported, then fail on the first run. 

What happened is the initial run succeeded, but the consecutive runs failed with an error `When searching for a relation, dbt found an approximate match Instead of guessing
  which relation to use, dbt will move on`.

### System information
The output of `dbt --version`:
```
installed version: 0.13.1
   latest version: 0.13.1

Up to date!
```

The operating system you're running on:

macos 10.14.5, but it also failed in out kubernetes cluster running linux image

The python version you're using (probably the output of `python --version`)
Python 2.7.10

### Steps to reproduce

I created 2 files:
- mixed_CASE_test.sql
- UPPER_CASE_TEST.sql

both with same contents:

```
SELECT 1
```

First run is successful:

```
dbt run -m UPPER_CASE_TEST mixed_CASE_test
Running with dbt=0.13.1
Found 350 models, 103 tests, 0 archives, 2 analyses, 218 macros, 8 operations, 2 seed files, 0 sources

07:34:39 | Concurrency: 1 threads (target='dev')
07:34:39 |
07:34:39 | 1 of 2 START view model sbochniak_base_ga.UPPER_CASE_TEST............ [RUN]
07:34:42 | 1 of 2 OK created view model sbochniak_base_ga.UPPER_CASE_TEST....... [CREATE VIEW in 2.61s]
07:34:42 | 2 of 2 START view model sbochniak_base_ga.mixed_CASE_test............ [RUN]
07:34:45 | 2 of 2 OK created view model sbochniak_base_ga.mixed_CASE_test....... [CREATE VIEW in 2.29s]
07:34:50 |
07:34:50 | Finished running 2 view models in 17.26s.

Completed successfully

Done. PASS=2 ERROR=0 SKIP=0 TOTAL=2
```
Consecutive run fails:

```
dbt run -m UPPER_CASE_TEST mixed_CASE_test
Running with dbt=0.13.1
Found 350 models, 103 tests, 0 archives, 2 analyses, 218 macros, 8 operations, 2 seed files, 0 sources

07:40:36 | Concurrency: 1 threads (target='dev')
07:40:36 |
07:40:36 | 1 of 2 START view model sbochniak_base_ga.UPPER_CASE_TEST............ [RUN]
07:40:37 | 1 of 2 ERROR creating view model sbochniak_base_ga.UPPER_CASE_TEST... [ERROR in 0.04s]
07:40:37 | 2 of 2 START view model sbochniak_base_ga.mixed_CASE_test............ [RUN]
07:40:37 | 2 of 2 ERROR creating view model sbochniak_base_ga.mixed_CASE_test... [ERROR in 0.02s]
07:40:40 |
07:40:40 | Finished running 2 view models in 9.79s.

Completed with 2 errors:

Compilation Error in model UPPER_CASE_TEST (models/base/ga/customer_funnels/UPPER_CASE_TEST.sql)
  When searching for a relation, dbt found an approximate match. Instead of guessing
  which relation to use, dbt will move on. Please delete "datalake"."sbochniak_base_ga"."upper_case_test", or rename it to be less ambiguous.
  Searched for: "datalake"."sbochniak_base_ga"."UPPER_CASE_TEST"
  Found: "datalake"."sbochniak_base_ga"."upper_case_test"

  > in macro materialization_view_default (macros/materializations/view/view.sql)
  > called by model UPPER_CASE_TEST (models/base/ga/customer_funnels/UPPER_CASE_TEST.sql)

Compilation Error in model mixed_CASE_test (models/base/ga/customer_funnels/mixed_CASE_test.sql)
  When searching for a relation, dbt found an approximate match. Instead of guessing
  which relation to use, dbt will move on. Please delete "datalake"."sbochniak_base_ga"."mixed_case_test", or rename it to be less ambiguous.
  Searched for: "datalake"."sbochniak_base_ga"."mixed_CASE_test"
  Found: "datalake"."sbochniak_base_ga"."mixed_case_test"

  > in macro materialization_view_default (macros/materializations/view/view.sql)
  > called by model mixed_CASE_test (models/base/ga/customer_funnels/mixed_CASE_test.sql)

Done. PASS=0 ERROR=2 SKIP=0 TOTAL=2
```

### PR DESCRIPTION
**Pull request by beckjake**
Fixes #1555 

This might fix #1557 - hard to say as I couldn't figure out how to reproduce this one. I agree it's probably related though.

When dbt creates a relation in the db, add a special flag to the relation (defaults to False)
When checking a node name match:
 - if that flag is present and quoting is disabled, do a lowercase compare
 - otherwise remain case sensitive

### CODE REVIEW

**Comment by beckjake** [comment]
Oh, we do want to tweak the plugin setup script! Great point.

**Comment by beckjake** [comment]
I just checked and (contrary to my initial assumption) we shouldn't need to update the adapter plugin script, the script assumes you don't need to override `Relation` (phew!)

**Comment by beckjake** [comment]
Third party plugins that override `Relation` will need to make changes though, yeah - I guess spark is one of those. It's a pretty minor change...

**Comment by drewbanin** [comment]
ok, that's good. Let's merge this PR, then tackle dbt-spark separately. I'll make an issue over there to re-pin to 0.14.0 and can include this change in the description

**Pull request merged**
