### PR TITLE
Clickable doc serve URL

### LINKED ISSUE #2027: Minor rendering bug for clickable `docs serve` output
### Describe the bug

When running `dbt serve` the printout of the url where the docs are served is rendering with a period ('.') immediately adjacent to the link. This is a minor issue but it prevents link detection from working correctly by terminals (VS Code in my case) which automatically detect URLs and render them as hyperlinks. In this case, the output is correctly parsed as a URL but because the URL includes a '.' at the end, it reaches a dead end (equivalent to pasting `http://localhost:8081.` in chrome address bar).

```
To access from your browser, navigate to http://localhost:8080.
```

### Steps To Reproduce

1. Run `dbt docs serve`

### Expected behavior

Ideally, the printout would be rendered as:

```
To access from your browser, navigate to: http://localhost:8080
```

### Screenshots and log output

```
Running with dbt=0.13.0
Serving docs at 0.0.0.0:8080
To access from your browser, navigate to http://localhost:8080.
Press Ctrl+C to exit.
```

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
Running with dbt=0.13.0
```

**The operating system you're using:**

**The output of `python --version`:**

### PR DESCRIPTION
**Pull request by aaronsteers**
Fixes #2027 - this resolves an issue where the period ('.') after the URL causes hyperlink-detection to work incorrectly in tools like VS Code.

Before this fix, the link is clickable but the user does not reach the desired page due to the included '.' in the passed url.

After this fix, the link is clickable and also directs to the correct URL.

### CODE REVIEW

**Comment by aaronsteers** [comment]
@drewbanin - Thanks for your review of the previous PR (#2027). Resubmitted as requsted with the target `dev/barbara-gittings`

Thanks! 👍

**Comment by drewbanin** [comment]
Thanks @aaronsteers - this looks pretty good to me!

Are you able to sign the CLA attached above? It's a little funny for this PR, but we do require all contributors to sign the CLA as a policy. Let me know!

**Comment by aaronsteers** [comment]
@drewbanin - This is complete. Thx!

**Comment by aaronsteers** [comment]
Tried pushing an additional commit to see if CLA bot would be happy - no go unfortunately. Please lmk if I need to take some additional action. Thanks!

**Comment by drewbanin** [comment]
@aaronsteers sorry bout that - you're all set now! Thanks! @cla-bot check

**Comment by aaronsteers** [comment]
Awesome, thanks @drewbanin!

**Pull request merged**
