### PR TITLE
Adds missing comma to `dbt compile` help text

### LINKED ISSUE #2388: `dbt compile` help text is missing a comma
### Describe the bug
`dbt -h` outputs:
```
...
    compile             Generates executable SQL from source model, test, and
                        analysis files. Compiled SQL files are written to the
                        target/ directory.
...
```
but a 'source model' is not a construct within dbt, there are sources _and_ models.

### Steps To Reproduce
`dbt -h`

### Expected behavior
I'd expect a comma between each object the help text describes, especially since the oxford comma is used before the word 'and'
### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [x] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
installed version: 0.15.1
```
(but this is still true in dbt 0.16.x and in the current master branch)
**The operating system you're using:**
debian buster
**The output of `python --version`:**
Python 3.7.4.

### PR DESCRIPTION
**Pull request by sethwoodworth**
resolves #2388 

### Description

Adds a comma to the help text for `dbt compile`

### Checklist
 - [x] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
 - [x] I have run this code in development and it appears to resolve the stated issue
 - [x] This PR includes tests, or tests are not required/relevant for this PR
 - [x] I have updated the `CHANGELOG.md` and added information about my change to the "dbt next" section.

### CODE REVIEW

**Comment by beckjake** [comment]
@cla-bot check

**Comment by beckjake** [comment]
Thanks for bringing this to our attention @sethwoodworth! I think this message actually predates the existence of "sources" in dbt and the "source" there is referring to the concept of those SQL files as "source code".

This is copy-related, so cc @drewbanin - what should this actually say?

**Comment by drewbanin** [comment]
ha - you're right @beckjake - this does predate sources in dbt. Either way though, I think the copy here LGTM :)

**Comment by drewbanin** [comment]
@sethwoodworth if you're able to update the `CHANGELOG.md` file, we can get this merged! It's a small change, but we want to make sure you get credit for it in the release notes :)

Thanks again for the attention to detail here!

**Comment by sethwoodworth** [comment]
@drewbanin PR updated with CHANGELOG.md addition :+1:

**Comment by beckjake** [comment]
I've kicked off the test suite (though it's more of a formality in this PR's case). Once they pass, I'll merge this. Thanks for your contribution @sethwoodworth!

**Pull request merged**
