### PR TITLE
add a "docs" field to models (#1671)

### PR DESCRIPTION
**Pull request by beckjake**
Fixes the dbt-core side of #1671

It's parsed from the "models" block in schema.yml. It contains one field, a bool named "show" which defaults to True.

```
version: 2

models:
  - name: model
    description: "The test model"
    docs:
      show: false
```

This has no impact besides adding the field to compiled output, and this PR does not update the docs page to make any use of the field.

### CODE REVIEW

**Comment by mike-weinberg** [comment]
@beckjake @drewbanin just curious if you saw https://github.com/fishtown-analytics/dbt/issues/1671#issuecomment-570708988 -- considerations for forward compatibility with potential future doc configuration features

**Comment by beckjake** [comment]
@mike-weinberg I didn't notice it, but `show` vs `hide` is more of an aesthetic thing, right? And with this model it seems pretty straightforward to do the same thing as you suggested, except inverted (opt-in instead of out once you commit to making changes):

```yaml
docs:
   show: lineage
```
or
```yaml
docs:
    show:
        - lineage
```
or whatever else we want to support. So I guess I feel pretty good about forwards compatibility, unless there's something I'm missing?

But of course I will defer to drew on this - I don't have any strong feelings on the matter, and it's easy enough to change.

**Comment by beckjake** [comment]
However, I did think about this over the weekend and realized that macros and anything else that has docs should get this treatment as well, so I'm going to make some changes!

**Comment by beckjake** [comment]
I'll rebase this - I kind of expected removing `docrefs` to conflict with this new field.

**Comment by drewbanin** [comment]
@mike-weinberg let me hit you back in the open issue

**Pull request merged**
