### PR TITLE
Handle circular refs

### PR DESCRIPTION
**Pull request by drewbanin**

### CODE REVIEW

**Comment by cmcarthur** [comment]
@drewbanin were you able to make any headway on this?

**Comment by drewbanin** [comment]
@cmcarthur not yet, but planning on carving out some time today. I think we're close!

**Comment by drewbanin** [comment]
I remain perplexed by this -- networkx seems to find a cycle when `orientation='reverse'`, but not when `orientation='original'`. Moreover, it's not clear to me how the orientation in a digraph is significant when finding cycles.

I have an example project from a dbt user which contains a cycle, but runs without error on 0.9.0. Interestingly, if I remove all of the models _except_ for the ones that participate in the cycle, then then dbt correctly identifies that the cycle exists. This makes me think that there's some other dbt issue (likely with ephemeral models?) which contributes to this issue.

**Comment by drewbanin** [comment]
I think I've narrowed this down to a bug in networkx v1.11. Check this out:
```
> /Users/drew/fishtown/dbt/dbt/linker.py(44)find_cycles()
     34         try:
     35             # cycles = nx.algorithms.find_cycle(self.graph) # Old approach
     36             cycles = list(nx.simple_cycles(self.graph)) # Potential new approach
     37
     38         except nx.exception.NetworkXNoCycle:
     39             return None
     40
     41         import ipdb; ipdb.set_trace()
     42
---> 43         if cycles:
     44             return " --> ".join([".".join(node) for node in cycles])


ipdb> cycles
[['model.project.model_1', 'model.project.model_2']]
ipdb> nx.algorithms.find_cycle(self.graph)
*** networkx.exception.NetworkXNoCycle: No cycle found.
ipdb>
```

So, `nx.simple_cycles` finds the cycle, but `nx.algorithms.find_cycle` does not! The fix is provided [here](https://github.com/networkx/networkx/pull/2473), but I think that would require us to upgrade to version 2.x of networkx. We should do that eventually, but I might reswizzle this to use `nx.simple_cycles` in the meantime

**Comment by drewbanin** [comment]
I've tested this change with a bunch of our Fishtown jobs that failed in Sinter due to a cycle which wasn't correctly reported. It picked up on all of them! I'll feel really good about merging this once the tests pass

**Comment by cmcarthur** [comment]
aw yeah! nice find

**Comment by drewbanin** [comment]
This was due to a Networkx bug. More info here: https://github.com/networkx/networkx/pull/2473

**Pull request merged**
