### PR TITLE
🔨 Add ssh-client + update git using debian backports in Docker image

### LINKED ISSUE #3337: Need a more recent version of git, and ssh-client installed in the dbt Docker image
### Describe the feature

I would like `ssh-client` to be added, and `git` to be updated in the dbt Docker image.

### Describe alternatives you've considered

Right now, at Earnest, we modify the dbt Docker image as part of the CI process

### Additional context

Now, dbt deps supports [using a subdirectory](https://github.com/fishtown-analytics/dbt/pull/3267) and using a specific [commit hash](https://github.com/fishtown-analytics/dbt/pull/3270), and we integrated those features into our CI.

However we need to install `ssh-client` and update `git` in order to be able to pull our shared dbt package which is hosted in a private GitHub repository.

### Who will this benefit?

People using the dbt image and pulling dependencies from repositories using ssh.

### Are you interested in contributing this feature?

Yes! However, since I last had a look, the Docker image changed quite a bit.

If someone could just help me out building the Docker image locally, I could test this with our Earnest CI and also check that the packages installed don't increase significantly the size of the image.

### PR DESCRIPTION
**Pull request by dmateusp**
resolves #3337

### Description

Adds `ssh-client` and updates the `git` version (using backports) to enable using `dbt deps` with the Docker image, on private GitHub repositories, through SSH

### Checklist
 - [X] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
 - [x] I have run this code in development and it appears to resolve the stated issue **-- TODO: please help me out, the Docker image changed quite a bit since I last played with it, and I'm not sure how to get it to build locally with the new `--build-arg`s**
 - [X] This PR includes tests, or tests are not required/relevant for this PR -- note: the tests run on a different Docker image
 - [X] I have updated the `CHANGELOG.md` and added information about my change to the "dbt next" section.

### CODE REVIEW

**Comment by jtcohen6** [comment]
> TODO: please help me out, the Docker image changed quite a bit since I last played with it, and I'm not sure how to get it to build locally with the new `--build-arg`s

This is a bit outside my wheelhouse... @kwigley any chance you could give a pointer?

**Comment by kwigley** [comment]
@dmateusp this seems totally reasonable, I was able to test locally locally with success and the image size didn't seem to change too much. I'd love to have you test this out as well with our wacky build args before merging.

The build args are specifically meant for the build workflow that is set up, we'd have to move some things around in that process to make these build args a little more reasonable. This is something I'd like to do to make this more accessible.

In the meantime, here is a workaround. `BASE_REQUIREMENTS_SRC_PATH` can point to any file in `docker/requirements`, these are 3rd party dependencies of dbt. `WHEEL_REQUIREMENTS_SRC_PATH` is meant to point file listing paths to the dbt packages, but for this it can be the path to a file that contains the `dbt` requirement ([literally a requirements file](https://gist.github.com/kwigley/1a945c1a27bec34f17223cc06c48a368) with just `dbt==0.19.1` in it). `DIST_PATH` would point to where the python distribution files generated during the build process live, so that they can be copied into the image. This is pointless for testing this out, this can point to any directory. This might throw off the image size a little. Putting this together:

```
docker build -f docker/Dockerfile . --build-arg  BASE_REQUIREMENTS_SRC_PATH=./docker/requirements/requirements.0.19.1.txt --build-arg WHEEL_REQUIREMENTS_SRC_PATH=./docker/requirements/wheels.txt --build-arg DIST_PATH=docker -t test
```
where `./docker/requirements/wheels.txt` is the new file I created for the dbt requirement (0.19.1 in this case). Let me know how this goes.. this should be easier to do 😅

**Comment by dmateusp** [comment]
@kwigley thank you for sharing the steps! I published `dmateusp/dbt:0.20.0b1` and was able to confirm that our internal build can pull dependencies now without needing to install sftp and git anymore

**Review by kwigley — APPROVED** [review]
Thanks @dmateusp!

**Comment by dmateusp** [comment]
Thanks for merging :) @kwigley are you going to push a new version of the Docker image to dockerhub or should I wait for the next dbt version ?

**Comment by kwigley** [comment]
@dmateusp publishing images is so coupled with the automated release process, it may have to wait for the next release. I'll update if this is not the case!

**Pull request merged**
