### PR TITLE
Updating triggers to not have duplicate runs

### PR DESCRIPTION
**Pull request by leahwicz**
### Description

Using `pull_request_target` and `pull_request` is causing duplicate triggers. Removing `pull_request_target` since that is less secure of an option. The trade off is that for PR's from a fork we will have to manually approve they run the tests. If this starts to hinder contributors, we can go back and reconsider the trigger type.

I also added CI for a few more important branches for `push` 

### Checklist
 - [x] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
 - [ ] I have run this code in development and it appears to resolve the stated issue
 - [ ] This PR includes tests, or tests are not required/relevant for this PR
 - [ ] I have updated the `CHANGELOG.md` and added information about my change to the "dbt next" section.

### CODE REVIEW

**Comment by jtcohen6** [comment]
> for PR's from a fork we will have to manually approve they run the tests

What does the manual approval process look like? Definitely ideal version is, the tests just run. If one of us has to press a button, that's still better than checking out a commit locally and pushing to a branch named `pr/1234`.

**Comment by leahwicz** [comment]
> > for PR's from a fork we will have to manually approve they run the tests
> 
> What does the manual approval process look like? Definitely ideal version is, the tests just run. If one of us has to press a UI button, that's still better than checking out a commit locally and pushing to a branch named `pr/1234`.

@jtcohen6 It would be a button in the UI. We can make it automatic if we want to but we expose our Snowflake/Redshift/Bigquery test creds which I guess we have been doing anyway (looks like they are just for integration tests). It's a safer practice to do this but if we aren't too concerned with those test creds we can just make it automatic

**Comment by nathaniel-may** [comment]
I'm ok with it being more permissive for now and we can reign it in when it becomes a problem. Mostly because we'll have to do more steps than this to actually protect ourselves so we might as well enjoy the convenience for now too.

**Comment by jtcohen6** [comment]
> if we want to but we expose our Snowflake/Redshift/Bigquery test creds which I guess we have been doing anyway (looks like they are just for integration tests)

Right on—these are totally sandboxed instances, with no sensitive data, and aggressive resource limits to prevent any bad behavior

**Comment by leahwicz** [comment]
@nathaniel-may @jtcohen6 ok I changed it to trigger for forks too so we won't need any manual intervention

**Review by jtcohen6 — APPROVED** [review]

**Pull request merged**
