### PR TITLE
Use original path to mimick resource subdirectory structure

### LINKED ISSUE #2173: compiled "analysis" code writing to wrong target directory
### Describe the bug
I have a custom path other than "analysis" for some SQL that I want compiled by not run. I ran
- dbt clean
- dbt deps
- dbt compile
The SQL files that are in my custom analysis path were successfully compiled. However the path where the compiled code lives is: /target/compiled/customer_data_model/analysis. I'd expect it to be in /target/compiled/customer_data_model/custom-analysis-path

### Steps To Reproduce

- I set my analysis path in my dbt_project to "test_paths."
- I created a model in the directory "test_paths" called "test.sql" with "select 1 as test" as the SQL
- I ran dbt clean, dbt deps, dbt compile
- The test.sql model was compiled but the resulting compiled code lives in target/compiled/customer_data_model/**analysis**

### Expected behavior
I'd expect the compiled code to live in target/compiled/customer_data_model/**test_paths**

### Screenshots and log output
If applicable, add screenshots or log output to help explain your problem.

### System information
**Which database are you using dbt with?**
- [x ] postgres
- [ ] redshift
- [ ] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
0.15.2
```

**The operating system you're using:**
10.15.3

**The output of `python --version`:**
3.7.4

### PR DESCRIPTION
**Pull request by franloza**
Resolves #2173

### Description

I'm using the original path when compiling to preserve the original folder structure.

### Checklist
 - [x] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
 - [x] I have run this code in development and it appears to resolve the stated issue
 - [x] This PR includes tests, or tests are not required/relevant for this PR
 - [x] I have updated the `CHANGELOG.md` and added information about my change to the "dbt next" section.

### CODE REVIEW

**Comment by drewbanin** [comment]
Thanks for opening this PR @franloza!

It looks like the tests failed here -- there's going to be a bunch of changes to make in the test suite to make `actual == expected` for these changes. Before you go off an do all of that work, it would be good to have @beckjake take a look at your approach :)

**Comment by franloza** [comment]
@beckjake I have reproduced the error and the approach I have followed to solve the problem in 8f45ecebb4a0c08f4f8e247928d4367b88e7e169 is very similar to the one you have proposed.

If the basename of the path is equal, it means that is one-to-one relationship and we can use the original path safely. However, if the base name is not equal, it means that it is a many-to-one relationship and in that case, we need to consider the basename as a folder (like you proposed to do with `schema.yml`) and append the path to the original path.

Therefore, for the analysis file, the resulting full path would be `target/compiled/customer_data_model/test_paths/test.sql` whereas for a custom schema test would be `target/compiled/customer_data_model/models/base/schema.yml/schema_test/custom_base_customers_name.sql` .

What do you think about this approach? Do you think it is consistent with the original solution?

**Comment by beckjake** [comment]
@franloza Yeah, that sounds great!

**Comment by beckjake** [comment]
I'm merging this before these tests finish - this was all passing and the only conflict was in the changelog, which I've resolved.

**Pull request merged**
