### PR TITLE
Add logging to `dbt clean`

### PR DESCRIPTION
**Pull request by emilieschario**
This MR does two things:

1. It adds some small updates to the contributing docs to make it easier for someone to get started without getting lost in the documentation of other tools. 

2. It adds logging to the `dbt clean` task as outlined in https://github.com/fishtown-analytics/dbt/issues/1261.

A sample output on 0.13.0 might look like
```
(dbt36) >dbt clean
Running with dbt=0.13.0
Checking target/*
 Cleaned target/*
Checking dbt_modules/*
 Cleaned dbt_modules/*
Finished cleaning all paths.
```

### CODE REVIEW

**Comment by emilieschario** [comment]
@drewbanin I'd love to get your thoughts on this as is (or clarity on what else it needs).

**Comment by beckjake** [comment]
This looks good to me. Can you rebase off the existing `fishtown-analytics:dev/wilt-chamberlain`, or merge it in? #1378 in particular is the PR I'm interested in getting into your branch, so I can kick Windows tests off!

**Comment by emilieschario** [comment]
@beckjake should be good to kickoff now!

**Comment by cmcarthur** [comment]
@emilieschario I've reopened this PR with your commits against `dev/0.13.1` over here: https://github.com/fishtown-analytics/dbt/pull/1391. I'll merge that shortly. Thanks for contributing!!!

**Comment by emilieschario** [comment]
Thanks @cmcarthur!!

**Pull request closed without merging**
