### PR TITLE
Update google cloud dependencies

### PR DESCRIPTION
**Pull request by max-sixty**
resolves https://github.com/fishtown-analytics/dbt/issues/3155

### Description

As per the last one of these, another bump to latest.

These are now more stable, so you may want to only pin the major version — let me know if you'd like me to make that change.

### Checklist
 - [x] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
 - [ ] I have run this code in development and it appears to resolve the stated issue
 - [x] This PR includes tests, or tests are not required/relevant for this PR
 - [x] I have updated the `CHANGELOG.md` and added information about my change to the "dbt next" section.

### CODE REVIEW

**Comment by jtcohen6** [comment]
Thanks @max-sixty!

> These are now more stable, so you may want to only pin the major version — let me know if you'd like me to make that change.

I'd love to be in a place of having major-version boundaries for these. It's not such a chore to upgrade them every minor release, but tighter pins result in inevitable delays. Could you say a bit more about the improved stability, based on what you've observed / read / heard?

**Comment by max-sixty** [comment]
> I'd love to be in a place of having major-version boundaries for these. It's not such a chore to upgrade them every minor release, but tighter pins result in inevitable delays. Could you say a bit more about the improved stability, based on what you've observed / read / heard?

I don't have a more reliable signal than my own experience, unfortunately. I'm trying to think of a good one — maybe whether dbt has had to make any changes to its library when upgrading — do you know whether it has?

In my experience — this used to be a big problem and I used to complain about it — and in the last year at least, I haven't found it a problem at all.

**Comment by max-sixty** [comment]
Any thoughts on merging? I see 0.19.1 came out today.

**Comment by jtcohen6** [comment]
> maybe whether dbt has had to make any changes to its library when upgrading — do you know whether it has?

I don't believe we've had to do this for some time. At the same time, I know we see some deprecation warnings from the BigQuery python client, e.g.
```
Client.dataset is deprecated and will be removed in a future version. Use a string like 'my_project.my_dataset' or a cloud.google.bigquery.DatasetReference object, instead.
```

In any case, I think I'd be open to trying to relax the pins (major-version upper bounds instead of minor ones) in v0.20. We could merge that change now, and see if we run into any trouble between now and the final v0.20.0 release.

**Comment by max-sixty** [comment]
Great! Done!

**Comment by jtcohen6** [comment]
Nice, thank you! Could you also remove the associated comment ("these are more tightly pinned"), and add a changelog entry?

**Comment by max-sixty** [comment]
> Nice, thank you! Could you also remove the associated comment ("these are more tightly pinned"), and add a changelog entry?

Good spot, both done

**Review by jtcohen6 — APPROVED** [review]
Thanks @max-sixty!

**Pull request merged**
