### PR TITLE
fix docstring duplication error issue #2054

### PR DESCRIPTION
**Pull request by bubbomb**
This commit fixes the issue #2054

### CODE REVIEW

**Comment by drewbanin** [comment]
hey @bubbomb - can you rebase this onto `dev/barbara-gittings`? We're cutting an RC of 0.15.2 tomorrow and are no longer accepting PRs to the `dev/0.15.2` branch.

This looks really great so far! I saw your issue comment about adding tests. What do you think about adding a new test case for a sample project with two identically named docs block?

You can add a new test class like this one:
https://github.com/fishtown-analytics/dbt/blob/e080bfc79ab11a4d145de4c8da9d955c5e136d92/test/integration/035_docs_blocks/test_docs_blocks.py#L130-L147

And a new directory like this one (eg. `duplicated_names/`) that looks something like this:
https://github.com/fishtown-analytics/dbt/tree/dev/0.15.2/test/integration/035_docs_blocks/invalid_name_models

I can kick off the test suite once some tests are added here :)

**Comment by bubbomb** [comment]
thanks @drewbanin this is exactly what I was looking for. I messed around with a few other tests for a while but couldn't get things to work quite the way I wanted to. I'll give this a shot and let you know.

**Comment by bubbomb** [comment]
Would you like me to close this PR and submit a new PR to the dev/barbara-gittings branch?

**Comment by drewbanin** [comment]
It's up to you! You can totally do that, or if you're comfortable enough with git, you can also rebase your commits onto the latest `dev/barbara-gittings` and we can update the base branch in this PR!

I think that might look something like
```
git remote add fishtown https://github.com/fishtown-analytics/dbt.git
git fetch fishtown
git rebase -i fishtown/dev/barbara-gittings
```

If that becomes a big mess, you can certainly feel free to open a new PR for a branch off of `dev/barbara-gittings` :)

**Comment by drewbanin** [comment]
It looks like there are still some stray commits in here. If you'd prefer, please feel free to close this one and open up another PR for your change :)

**Comment by bubbomb** [comment]
Yea, that was a little odd. I just saw that too. No worries though I updated it.  Will this work or do you want me to open a new PR?

**Comment by beckjake** [comment]
Hey @bubbomb, this PR looks great!

The new test is failing, I believe you need the commented out `with self.assertRaises(...)` - this code fails during compile time, not run time, so you have to catch an exception instead of `expect_pass=False`: Just one of those fun quirks of our integration test system.

**Comment by bubbomb** [comment]
@beckjake crud... I must have left that commented out after messing around with a few things. I'll get a fix up for it.

**Comment by drewbanin** [comment]
@bubbomb can you mark this PR as "ready for review" if it's ready to merge? Thanks!

**Comment by beckjake** [comment]
Thanks so much for your contribution @bubbomb! This will get in to `0.16.0` (but missed the cutoff for `beta1`).

**Comment by bubbomb** [comment]
@beckjake @drewbanin no problem you guys were great to work with!

**Pull request merged**
