### PR TITLE
Check if a snowflake column exists before altering its comment

### LINKED ISSUE #3039: Improve Error Message for Persisted Comments on Columns
### Describe the bug
* When using [persisted_docs](https://docs.getdbt.com/reference/resource-configs/persist_docs/) for table columns in Snowflake, the error messaging could be improved in the specific case where you have a column in the `.yml` file that doesn't exist in the model
* Snowflake tries to comment on a table column that doesn't actually exist (since it's not in the model), resulting in an error. dbt passes through the snowflake error during the dbt run saying `Database Error ... invalid identifier '<colum_name>'` but this message could be potentially improved to direct you closer to the specific problem.

### Steps To Reproduce

`models/staging/stg_orders.sql`
```sql
{{ config(materialized='table') }}

with source as (
    select * from {{ ref('raw_orders') }}
)

select id as order_id from source /* No column called 'foo' */
```

--- 

`models/staging/schema.yml`
```yml
version: 2

models:
  - name: stg_orders
    columns:
      - name: order_id
        tests:
          - unique
          - not_null

      - name: foo
        description: 'test comment'
        tests:
          - not_null
```

---

`dbt_project.yml`
```yml
...
models:
  +persist_docs:
    columns: true
```

---

#### On snowflake:
Run `dbt run --models stg_orders`

```sh
Running with dbt=0.19.0
Found 8 models, 15 tests, 0 snapshots, 0 analyses, 143 macros, 0 operations, 3 seed files, 0 sources, 0 exposures

09:54:44 | Concurrency: 8 threads (target='dev')
09:54:44 | 
09:54:44 | 1 of 1 START table model eli.stg_orders.............................. [RUN]
09:54:48 | 1 of 1 ERROR creating table model eli.stg_orders..................... [ERROR in 3.56s]
09:54:51 | 
09:54:51 | Finished running 1 table model in 11.17s.

Completed with 1 error and 0 warnings:

Database Error in model stg_orders (models/staging/stg_orders.sql)
  000904 (42000): SQL compilation error: error line 5 at position 8
  invalid identifier 'FOO'
  compiled SQL at target/run/jaffle_shop/models/staging/stg_orders.sql

Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1
```
---

`dbt.log`

<details>
<summary> dbt.log </summary>

```
2021-01-28 18:00:42.714447 (Thread-1): Using snowflake connection "model.jaffle_shop.stg_orders".
2021-01-28 18:00:42.714515 (Thread-1): On model.jaffle_shop.stg_orders: /* {"app": "dbt", "dbt_version": "0.19.0", "profile_name": "jaffle_shop", "target_name": "dev", "node_id": "model.jaffle_shop.stg_orders"} */


      create or replace transient table DEV.eli.stg_orders  as
      (

with source as (
    select * from DEV.eli.raw_orders
)

select id as order_id from source /* No column called 'foo' */
      );
2021-01-28 18:00:44.407204 (Thread-1): SQL status: SUCCESS 1 in 1.69 seconds
2021-01-28 18:00:44.408124 (Thread-1): On model.jaffle_shop.stg_orders: COMMIT
2021-01-28 18:00:44.408251 (Thread-1): Using snowflake connection "model.jaffle_shop.stg_orders".
2021-01-28 18:00:44.408318 (Thread-1): On model.jaffle_shop.stg_orders: COMMIT
2021-01-28 18:00:44.607178 (Thread-1): SQL status: SUCCESS 1 in 0.20 seconds
2021-01-28 18:00:44.617705 (Thread-1): Using snowflake connection "model.jaffle_shop.stg_orders".
2021-01-28 18:00:44.617827 (Thread-1): On model.jaffle_shop.stg_orders: /* {"app": "dbt", "dbt_version": "0.19.0", "profile_name": "jaffle_shop", "target_name": "dev", "node_id": "model.jaffle_shop.stg_orders"} */

    alter table DEV.eli.stg_orders alter
    
        order_id COMMENT $$$$ ,
    
        foo COMMENT $$test comment$$ ;
2021-01-28 18:00:44.907090 (Thread-1): Snowflake query id: 0199ea98-04b1-6014-0008-f983000a5082
2021-01-28 18:00:44.907203 (Thread-1): Snowflake error: 000904 (42000): SQL compilation error: error line 5 at position 8
invalid identifier 'FOO'
2021-01-28 18:00:44.907587 (Thread-1): finished collecting timing info
2021-01-28 18:00:44.907807 (Thread-1): On model.jaffle_shop.stg_orders: Close
2021-01-28 18:00:45.260005 (Thread-1): Database Error in model stg_orders (models/staging/stg_orders.sql)
  000904 (42000): SQL compilation error: error line 5 at position 8
  invalid identifier 'FOO'
  compiled SQL at target/run/jaffle_shop/models/staging/stg_orders.sql
```

</details>

--- 

### Expected behavior
* Multiple members of my team including myself have struggled debugging this error message the first time it happens to us. It seems obvious in retrospect but in the moment it isn't clear that the column comment is the source of the error.
  * Because it happens during the `run`, it's not immediately obvious that the cause of the error is the "foo" column existing in the .yml but not the .sql model (we tend to mentally associate the .yml file only with the testing step)
  * Also, when you look at the target file `target/run/jaffle_shop/models/staging/stg_orders.sql` the comment commands aren't there, making debugging a bit harder
* I think this experience could be improved by having dbt raise it's own error to warn about trying to comment on columns that doesn't exist, rather than just passing through the snowflake error which isn't as direct (not sure about the experience on other dbs)

### Screenshots and log output
<details>
<summary> dbt.log </summary>

```
2021-01-28 18:00:42.714447 (Thread-1): Using snowflake connection "model.jaffle_shop.stg_orders".
2021-01-28 18:00:42.714515 (Thread-1): On model.jaffle_shop.stg_orders: /* {"app": "dbt", "dbt_version": "0.19.0", "profile_name": "jaffle_shop", "target_name": "dev", "node_id": "model.jaffle_shop.stg_orders"} */


      create or replace transient table DEV.eli.stg_orders  as
      (

with source as (
    select * from DEV.eli.raw_orders
)

select id as order_id from source /* No column called 'foo' */
      );
2021-01-28 18:00:44.407204 (Thread-1): SQL status: SUCCESS 1 in 1.69 seconds
2021-01-28 18:00:44.408124 (Thread-1): On model.jaffle_shop.stg_orders: COMMIT
2021-01-28 18:00:44.408251 (Thread-1): Using snowflake connection "model.jaffle_shop.stg_orders".
2021-01-28 18:00:44.408318 (Thread-1): On model.jaffle_shop.stg_orders: COMMIT
2021-01-28 18:00:44.607178 (Thread-1): SQL status: SUCCESS 1 in 0.20 seconds
2021-01-28 18:00:44.617705 (Thread-1): Using snowflake connection "model.jaffle_shop.stg_orders".
2021-01-28 18:00:44.617827 (Thread-1): On model.jaffle_shop.stg_orders: /* {"app": "dbt", "dbt_version": "0.19.0", "profile_name": "jaffle_shop", "target_name": "dev", "node_id": "model.jaffle_shop.stg_orders"} */

    alter table DEV.eli.stg_orders alter
    
        order_id COMMENT $$$$ ,
    
        foo COMMENT $$test comment$$ ;
2021-01-28 18:00:44.907090 (Thread-1): Snowflake query id: 0199ea98-04b1-6014-0008-f983000a5082
2021-01-28 18:00:44.907203 (Thread-1): Snowflake error: 000904 (42000): SQL compilation error: error line 5 at position 8
invalid identifier 'FOO'
2021-01-28 18:00:44.907587 (Thread-1): finished collecting timing info
2021-01-28 18:00:44.907807 (Thread-1): On model.jaffle_shop.stg_orders: Close
2021-01-28 18:00:45.260005 (Thread-1): Database Error in model stg_orders (models/staging/stg_orders.sql)
  000904 (42000): SQL compilation error: error line 5 at position 8
  invalid identifier 'FOO'
  compiled SQL at target/run/jaffle_shop/models/staging/stg_orders.sql
```

</details>

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [x] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
installed version: 0.19.0
   latest version: 0.19.0

Up to date!

Plugins:
  - bigquery: 0.19.0
  - snowflake: 0.19.0
  - redshift: 0.19.0
  - postgres: 0.19.0
```

**The operating system you're using:** Mac OS

**The output of `python --version`:** Python 3.8.5

### Additional context
I'm very interested in working on this issue myself but wanted to first see if anybody else had feedback or thoughts to share about it.

### PR DESCRIPTION
**Pull request by elikastelein**
Resolves #3039

### Description
* This PR modifies the "alter column comment" snowflake macro by breaking each column comment into a separate DDL statement, so that we can check that the column exists before attempting to  comment on it
* This helps avoid the confusing scenario of getting a database error for a column that doesn't appear in your model's .sql file 
* I couldn't find an equivalent to `comment if exists` in BQ, redshift, or postgres so I did this PR for snowflake only
* As mentioned in #3039, the downside of this PR is that breaking things up into multiple DDL statements causes dbt run to take longer. I hope this is okay since `persist_docs` defaults to off and users who are ultra-concerned with performance would most likely have it off anyways.

### Checklist
 - [x] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
 - [x] I have run this code in development and it appears to resolve the stated issue
 - [x] This PR includes tests, or tests are not required/relevant for this PR
 - [x] I have updated the `CHANGELOG.md` and added information about my change to the "dbt next" section.

### CODE REVIEW

**Comment by elikastelein** [comment]
I've just signed the CLA now

**Comment by kwigley** [comment]
@cla-bot check

**Review by jtcohen6 — COMMENTED** [review]
Nice one @elikastelein, this works for me locally!

Could you add a new test case to [`test/integration/060_persist_docs_test`](https://github.com/fishtown-analytics/dbt/tree/develop/test/integration/060_persist_docs_tests) for this functionality? This would look like a new models folder, `models-column-missing`, containing model that has a description defined on a column that does not actually exist. Then, a new test script (`TestPersistDocsColumnMissing`) that uses that model, runs dbt, and ensures it passes as expected. I believe BigQuery and (now) Snowflake will be able to handle this and pass, whereas Postgres and Redshift would fail. Let me know if you want any help, or more pointers to get started!

Could you also add a Changelog entry under v0.20.0 - Fixes, and add yourself to the list of contributors?

**Comment by jtcohen6** [comment]
Hey @elikastelein, hope you're well! Just wanted to check in and see if you'd be able to add a test case for this change? More than happy to help with any pointers :)

**Comment by elikastelein** [comment]
Hey @jtcohen6, thanks for the ping. Sorry about leaving this hanging. I'll get started on adding tests soon and let you know if I need any pointers

**Review by jtcohen6 — APPROVED** [review]
@elikastelein Nice work adding the test—I confirmed it fails without the change to `snowflake__alter_column_comment`, and succeeds with it.

This LGTM, thank you for the contribution (:

**Comment by elikastelein** [comment]
@jtcohen6 thanks so much for the help, your comments were very helpful

**Comment by joshuataylor** [comment]
Hi!

When running this, it runs one line per query. This slows down large tables with hundreds of columns, now taking minutes to run these instead of a few seconds.

This is because https://github.com/dbt-labs/dbt/commit/fffcd3b40423443a585a6ff1befaee74d47b6b30#diff-4e52d38c66fb471207fa26868ecc11715965558734704859a52b6bcfbc5c86cf now runs one query per line in sf, instead of putting it all in a single query.

**Pull request merged**
