### PR TITLE
Include external tables in get_columns_in_relation redshift adapter

### LINKED ISSUE #2753: get_columns_in_relation does not include columns from external tables in Redshift
### Describe the bug
get_columns_in_relation does not include columns from external tables in Redshift

### Steps To Reproduce
- Set up a Spectrum tables as a source in your project
- Use `adaptor.get_columns_in_relation(source(....))` in a macro

### Expected behavior
All the column names should be returned. 

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [x] redshift
- [ ] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
❯ dbt --version
installed version: 0.17.0
   latest version: 0.18.0

Your version of dbt is out of date! You can find instructions for upgrading here:
https://docs.getdbt.com/docs/installation

Plugins:
  - bigquery: 0.17.0
  - snowflake: 0.17.0
  - redshift: 0.17.0
  - postgres: 0.17.0

```

**The operating system you're using:**
MacOS Catalina

**The output of `python --version`:**
Python 3.7.7

### PR DESCRIPTION
**Pull request by aiguofer**
resolves #2753

### Description

This PR adds columns from external tables to get_columns_in_relation in the Redshift adapter. I'd be happy to add tests and update CHANGELOG if it makes sense.

### Checklist
 - [x] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
 - [x] I have run this code in development and it appears to resolve the stated issue
 - [ ] This PR includes tests, or tests are not required/relevant for this PR
 - [x] I have updated the `CHANGELOG.md` and added information about my change to the "dbt next" section.

### CODE REVIEW

**Comment by jtcohen6** [comment]
We need to fix a few issues with Redshift integration tests based on a [recent change](https://forums.aws.amazon.com/ann.jspa?annID=8055) they deployed. Jake is working on those fixes over [here](https://github.com/fishtown-analytics/dbt/pull/2752/commits/a4011170c52dd5b856fbca98147f26a664884c27), in a PR we'll merge quite soon.

**Comment by beckjake** [comment]
We also need to fix the default branch! It should probably be `dev/kiyoshi-kuromiya`, but this PR could probably be against `dev/0.18.1` if we wanted.

**Comment by aiguofer** [comment]
Great! happy to change the target of the PR, should I make it against `dev/kiyoshi-kuromiya` or `dev/0.18.1`?

I'll go ahead and add the `CHANGELOG` change as well, and happy to update the PR once those integration tests are merged (link took me to the report feature PR, I guess that's where those changes are?)

**Comment by aiguofer** [comment]
Actually, don't see a `dbt next` section in `CHANGELOG`... do I need to add that or do you guys update the `CHANGELOG` on release? if the latter, might want to update the PR template :)

**Comment by beckjake** [comment]
We should probably refer to it as the "Release TBD" version! Both 0.18.1 and dev/kiyoshi-kuromiya should have a line like that.

**Comment by aiguofer** [comment]
sorry for the spam... realized `dev/kiyoshi-kuromiya` is the future `0.19.0` version so rebased again against `dev/0.18.1`

**Review by beckjake — COMMENTED** [review]
This looks good. I'm not sure how we can effectively test this - do we need to create a spectrum table or something that we can query as a source in our test suite?

**Review by jtcohen6 — APPROVED** [review]
This looks good in my local testing. I need to figure out a long-term plan for staging spectrum tables in our testing env, since it's also a prerequisite to testing the [dbt-external-tables](https://github.com/fishtown-analytics/dbt-external-tables) package. In the meantime, a bunch of our existing integration tests use `adapter.get_columns_in_relation`, so we should quickly find out about any regressions introduced here.

I'll wait until some of the open PRs have been merged, and then get this in before v0.18.1.

**Pull request merged**
