### PR TITLE
Schema v1 v2 converter (#942)

### PR DESCRIPTION
**Pull request by beckjake**
Add a converter for schema v1 -> v2. I also included some fancy custom handling, like we discussed. There are some very basic tests as well, you can run them via `nosetests scripts/upgrade_dbt_schema_tests_v1_to_v2.py`. I didn't add them to the test harness since it's not clear we're even keeping this here, but I could easily do so.

I tested it out briefly on some of the `008_schema_tests_test` cases and everything does appear reasonable.

### CODE REVIEW

**Comment by drewbanin** [comment]
@beckjake this is really neat! Some initial thoughts:
- I pictured this working recursively on the whole `models/` directory, updating `schema.yml` files as it finds them. As it is, you can run the script in a loop over `find models -name schema.yml`, but I think it would be good if the script did this automatically.
- If we do make this recursively search through `models/`, can we check for the existence of `dbt_project.yml` and error out if it doesn't exist? I imagine this would go poorly if the script is run from a higher-level directory
- I like what you're doing with `--overwrite` and `--in-place`, but I think we can simplify this. How do you feel about the script "dry running" by default, then accepting an argument like `--replace` to actually update the schema.yml files with the new code?
- This is lower priority, but I noticed the output looks like:
```yml
models:
- columns:
  - name: collector_tstamp
    tests: [not_null]
  - name: event_id
    tests: [not_null, unique]
  name: stg_snowplow_events
version: 2
```

Is there an arg (`flow_style?`) to `yaml.safe_dump()` that makes the arrays render more vertically? Nbd if it's at all difficult -- I'm only interested in this if it's a one-line code change.

I need to play around with this some more but this is looking really great!

**Comment by beckjake** [comment]
@drewbanin I think I have addressed your comments and adjusted output accordingly, let me know what you think. On error, it currently bails on the file but not on the entire run, which seemed best to me. Unfortunately it looks like fixing the flow output of yaml.safe_dump would require writing our own yaml.SafeDumper, so I don't think we'll be doing that.

**Comment by beckjake** [comment]
That sounds like some effort, but pretty valuable. We control the schema, so it's doable and not super difficult, but it will be brittle. Let me see if I can get it done today, I guess?

**Comment by drewbanin** [comment]
I've been doing some more validation here. I think this script doesn't correctly handle this case:

```
model_name:
  constraints:
    dbt_utils.equality:
      - ref('other_table_name')
```

The output of this script is
```
- name: model_name
  tests:
  - dbt_utils.equality: ref('other_table_name')
```

whereas I think the test needs to be a dict, like:
```
- name: model_name
  tests:
  - dbt_utils.equality:
      compare_model: ref('other_table_name')
```

This just came up over [here](https://github.com/fishtown-analytics/dbt-utils/pull/77/files)). 
I think `compare_model` could equivalently be `arg` here instead

**Pull request merged**
